import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const labCategories = {
  Hematology: [
    { code: 'HEM-CBC', name: 'CBC / Complete Blood Count', price: 200 },
    { code: 'HEM-HB', name: 'Hemoglobin', price: 100 },
    { code: 'HEM-ESR', name: 'ESR', price: 100 },
    { code: 'HEM-RBC', name: 'RBC Count', price: 100 },
    { code: 'HEM-WBC', name: 'WBC / TLC Count', price: 100 },
    { code: 'HEM-DLC', name: 'Differential Leukocyte Count', price: 120 },
    { code: 'HEM-PLT', name: 'Platelet Count', price: 100 },
    { code: 'HEM-PBS', name: 'Peripheral Blood Smear', price: 200 },
    { code: 'HEM-RETIC', name: 'Reticulocyte Count', price: 200 },
    { code: 'HEM-MCV', name: 'MCV', price: 100 },
    { code: 'HEM-MCH', name: 'MCH', price: 100 },
    { code: 'HEM-MCHC', name: 'MCHC', price: 100 },
    { code: 'HEM-RDW', name: 'RDW', price: 100 },
    { code: 'HEM-PCV', name: 'Hematocrit / PCV', price: 100 },
    { code: 'HEM-BG', name: 'Blood Group & Rh Typing', price: 100 },
    { code: 'HEM-DCT', name: 'Direct Coombs Test', price: 300 },
    { code: 'HEM-ICT', name: 'Indirect Coombs Test', price: 350 },
    { code: 'HEM-PT', name: 'PT / Prothrombin Time', price: 300 },
    { code: 'HEM-INR', name: 'INR', price: 250 },
    { code: 'HEM-APTT', name: 'APTT', price: 350 },
    { code: 'HEM-DDIMER', name: 'D-Dimer', price: 800 },
    { code: 'HEM-FIB', name: 'Fibrinogen', price: 700 },
  ],
  Biochemistry: [
    { code: 'BIO-FBS', name: 'Fasting Blood Glucose', price: 80 },
    { code: 'BIO-PPBS', name: 'Post-Prandial Blood Glucose', price: 80 },
    { code: 'BIO-RBS', name: 'Random Blood Sugar', price: 80 },
    { code: 'BIO-CREAT', name: 'Creatinine', price: 150 },
    { code: 'BIO-UREA', name: 'Blood Urea', price: 150 },
    { code: 'BIO-BUN', name: 'BUN', price: 150 },
    { code: 'BIO-UA', name: 'Uric Acid', price: 150 },
    { code: 'BIO-CA', name: 'Calcium', price: 200 },
    { code: 'BIO-PHOS', name: 'Phosphorus', price: 200 },
    { code: 'BIO-MG', name: 'Magnesium', price: 300 },
    { code: 'BIO-TP', name: 'Total Protein', price: 150 },
    { code: 'BIO-ALB', name: 'Albumin', price: 150 },
    { code: 'BIO-GLOB', name: 'Globulin', price: 150 },
    { code: 'BIO-AMY', name: 'Amylase', price: 400 },
    { code: 'BIO-LIP', name: 'Lipase', price: 500 },
    { code: 'BIO-LDH', name: 'LDH', price: 400 },
    { code: 'BIO-CPK', name: 'CPK / CK', price: 400 },
    { code: 'BIO-CKMB', name: 'CK-MB', price: 500 },
    { code: 'BIO-CRP', name: 'CRP', price: 300 },
    { code: 'BIO-HSCRP', name: 'hs-CRP', price: 600 },
    { code: 'BIO-FERR', name: 'Ferritin', price: 700 },
    { code: 'BIO-HCY', name: 'Homocysteine', price: 900 },
  ],
  'Liver Function': [
    { code: 'LFT-FULL', name: 'Liver Function Test / LFT', price: 700 },
    { code: 'LFT-TBIL', name: 'Total Bilirubin', price: 150 },
    { code: 'LFT-DBIL', name: 'Direct Bilirubin', price: 150 },
    { code: 'LFT-IBIL', name: 'Indirect Bilirubin', price: 150 },
    { code: 'LFT-SGOT', name: 'SGOT / AST', price: 150 },
    { code: 'LFT-SGPT', name: 'SGPT / ALT', price: 150 },
    { code: 'LFT-ALP', name: 'Alkaline Phosphatase', price: 200 },
    { code: 'LFT-GGT', name: 'GGT', price: 250 },
    { code: 'LFT-TP', name: 'Total Protein', price: 150 },
    { code: 'LFT-ALB', name: 'Albumin', price: 150 },
    { code: 'LFT-GLOB', name: 'Globulin', price: 150 },
    { code: 'LFT-AG', name: 'A/G Ratio', price: 150 },
  ],
  'Kidney / Renal': [
    { code: 'KFT-FULL', name: 'Kidney Function Test / KFT', price: 600 },
    { code: 'RFT-FULL', name: 'Renal Function Test / RFT', price: 600 },
    { code: 'KFT-CREAT', name: 'Serum Creatinine', price: 150 },
    { code: 'KFT-UREA', name: 'Blood Urea', price: 150 },
    { code: 'KFT-BUN', name: 'BUN', price: 150 },
    { code: 'KFT-UA', name: 'Uric Acid', price: 150 },
    { code: 'KFT-CA', name: 'Calcium', price: 200 },
    { code: 'KFT-PHOS', name: 'Phosphorus', price: 200 },
    { code: 'KFT-NA', name: 'Sodium', price: 200 },
    { code: 'KFT-K', name: 'Potassium', price: 200 },
    { code: 'KFT-CL', name: 'Chloride', price: 200 },
    { code: 'KFT-EGFR', name: 'eGFR', price: 200 },
    { code: 'KFT-UMALB', name: 'Urine Microalbumin', price: 500 },
    { code: 'KFT-ACR', name: 'Albumin / Creatinine Ratio', price: 500 },
  ],
  'Lipid Profile': [
    { code: 'LIP-FULL', name: 'Lipid Profile', price: 600 },
    { code: 'LIP-TC', name: 'Total Cholesterol', price: 150 },
    { code: 'LIP-HDL', name: 'HDL Cholesterol', price: 200 },
    { code: 'LIP-LDL', name: 'LDL Cholesterol', price: 200 },
    { code: 'LIP-VLDL', name: 'VLDL Cholesterol', price: 150 },
    { code: 'LIP-TG', name: 'Triglycerides', price: 150 },
    { code: 'LIP-CHDL', name: 'Cholesterol / HDL Ratio', price: 150 },
    { code: 'LIP-LDLHDL', name: 'LDL / HDL Ratio', price: 150 },
    { code: 'LIP-NHDL', name: 'Non-HDL Cholesterol', price: 150 },
  ],
  Thyroid: [
    { code: 'THY-FULL', name: 'Thyroid Profile – T3/T4/TSH', price: 500 },
    { code: 'THY-TSH', name: 'TSH', price: 250 },
    { code: 'THY-T3', name: 'T3', price: 200 },
    { code: 'THY-T4', name: 'T4', price: 200 },
    { code: 'THY-FT3', name: 'Free T3', price: 350 },
    { code: 'THY-FT4', name: 'Free T4', price: 350 },
    { code: 'THY-ATPO', name: 'Anti-TPO Antibody', price: 800 },
    { code: 'THY-ATG', name: 'Anti-Thyroglobulin Antibody', price: 800 },
    { code: 'THY-TG', name: 'Thyroglobulin', price: 900 },
  ],
  'Vitamins & Minerals': [
    { code: 'VIT-B12', name: 'Vitamin B12', price: 650 },
    { code: 'VIT-D', name: 'Vitamin D – 25 OH', price: 1200 },
    { code: 'VIT-B1', name: 'Vitamin B1', price: 1500 },
    { code: 'VIT-B6', name: 'Vitamin B6', price: 1500 },
    { code: 'VIT-C', name: 'Vitamin C', price: 2000 },
    { code: 'VIT-FOL', name: 'Folate / Folic Acid', price: 600 },
    { code: 'MIN-FE', name: 'Iron', price: 250 },
    { code: 'MIN-TIBC', name: 'TIBC', price: 400 },
    { code: 'MIN-TRF', name: 'Transferrin', price: 800 },
    { code: 'MIN-FEPRO', name: 'Iron Profile', price: 800 },
    { code: 'MIN-FERR', name: 'Ferritin', price: 700 },
    { code: 'MIN-CA', name: 'Calcium', price: 200 },
    { code: 'MIN-MG', name: 'Magnesium', price: 300 },
    { code: 'MIN-PHOS', name: 'Phosphorus', price: 200 },
    { code: 'MIN-ZN', name: 'Zinc', price: 700 },
    { code: 'MIN-CU', name: 'Copper', price: 800 },
  ],
  Diabetes: [
    { code: 'DIA-FBS', name: 'Fasting Blood Sugar', price: 80 },
    { code: 'DIA-PPBS', name: 'Post-Prandial Blood Sugar', price: 80 },
    { code: 'DIA-RBS', name: 'Random Blood Sugar', price: 80 },
    { code: 'DIA-HBA1C', name: 'HbA1c', price: 500 },
    { code: 'DIA-FINS', name: 'Fasting Insulin', price: 500 },
    { code: 'DIA-CPEP', name: 'C-Peptide', price: 800 },
    { code: 'DIA-UGLU', name: 'Urine Glucose', price: 100 },
    { code: 'DIA-UKET', name: 'Urine Ketones', price: 100 },
    { code: 'DIA-UMALB', name: 'Microalbumin', price: 500 },
  ],
  'Infection & Fever': [
    { code: 'INF-DENGNS1', name: 'Dengue NS1 Antigen', price: 500 },
    { code: 'INF-DENGIGG', name: 'Dengue IgG', price: 500 },
    { code: 'INF-DENGIGM', name: 'Dengue IgM', price: 500 },
    { code: 'INF-DENGGM', name: 'Dengue IgG + IgM', price: 800 },
    { code: 'INF-MALP', name: 'Malaria Parasite Test', price: 300 },
    { code: 'INF-MALA', name: 'Malaria Antigen', price: 400 },
    { code: 'INF-WIDAL', name: 'Widal Test', price: 200 },
    { code: 'INF-TYPIGM', name: 'Typhoid IgM', price: 500 },
    { code: 'INF-CRP', name: 'CRP', price: 300 },
    { code: 'INF-PCT', name: 'Procalcitonin', price: 1200 },
    { code: 'INF-BCUL', name: 'Blood Culture', price: 1200 },
    { code: 'INF-UCUL', name: 'Urine Culture', price: 700 },
    { code: 'INF-SCUL', name: 'Stool Culture', price: 700 },
    { code: 'INF-HPIGG', name: 'H. pylori IgG', price: 700 },
    { code: 'INF-HPAG', name: 'H. pylori Antigen', price: 900 },
    { code: 'INF-ASO', name: 'ASO Titre', price: 350 },
    { code: 'INF-VDRL', name: 'VDRL', price: 200 },
    { code: 'INF-RPR', name: 'RPR', price: 300 },
  ],
  'Serology / Viral': [
    { code: 'SER-HIV', name: 'HIV 1 & 2', price: 350 },
    { code: 'SER-HBSAG', name: 'HBsAg', price: 350 },
    { code: 'SER-AHCV', name: 'Anti-HCV', price: 500 },
    { code: 'SER-HIVELISA', name: 'HIV ELISA', price: 500 },
    { code: 'SER-HIVVL', name: 'HIV Viral Load', price: 2500 },
    { code: 'SER-HBSAGQ', name: 'HBsAg Quantitative', price: 800 },
    { code: 'SER-HBEAG', name: 'HBeAg', price: 700 },
    { code: 'SER-AHBS', name: 'Anti-HBs', price: 700 },
    { code: 'SER-AHBCT', name: 'Anti-HBc Total', price: 700 },
    { code: 'SER-AHBCM', name: 'Anti-HBc IgM', price: 800 },
    { code: 'SER-HCVRNA', name: 'HCV RNA PCR', price: 2500 },
    { code: 'SER-CMVIGG', name: 'CMV IgG', price: 700 },
    { code: 'SER-CMVIGM', name: 'CMV IgM', price: 700 },
    { code: 'SER-EBVIGG', name: 'EBV IgG', price: 800 },
    { code: 'SER-EBVIGM', name: 'EBV IgM', price: 800 },
    { code: 'SER-RUBIGG', name: 'Rubella IgG', price: 700 },
    { code: 'SER-RUBIGM', name: 'Rubella IgM', price: 700 },
    { code: 'SER-HSV1', name: 'HSV-1 IgG', price: 700 },
    { code: 'SER-HSV2', name: 'HSV-2 IgG', price: 700 },
  ],
  'Urine Tests': [
    { code: 'URI-RM', name: 'Urine Routine & Microscopy', price: 100 },
    { code: 'URI-CE', name: 'Urine Complete Examination', price: 150 },
    { code: 'URI-PT', name: 'Urine Pregnancy Test', price: 150 },
    { code: 'URI-CUL', name: 'Urine Culture', price: 700 },
    { code: 'URI-PRO', name: 'Urine Protein', price: 100 },
    { code: 'URI-SUG', name: 'Urine Sugar', price: 100 },
    { code: 'URI-KET', name: 'Urine Ketones', price: 100 },
    { code: 'URI-MALB', name: 'Urine Microalbumin', price: 500 },
    { code: 'URI-BSP', name: 'Urine Bile Salt & Pigment', price: 150 },
    { code: 'URI-CA', name: 'Urine Calcium', price: 300 },
    { code: 'URI-24PRO', name: '24-Hour Urine Protein', price: 500 },
    { code: 'URI-24CRE', name: '24-Hour Urine Creatinine', price: 400 },
  ],
  'Stool Tests': [
    { code: 'STO-RE', name: 'Stool Routine Examination', price: 150 },
    { code: 'STO-OB', name: 'Stool Occult Blood', price: 250 },
    { code: 'STO-CUL', name: 'Stool Culture', price: 700 },
    { code: 'STO-OP', name: 'Stool for Ova & Parasites', price: 250 },
    { code: 'STO-RS', name: 'Stool Reducing Substance', price: 200 },
    { code: 'STO-FCAL', name: 'Fecal Calprotectin', price: 1500 },
  ],
  Hormones: [
    { code: 'HOR-TSTT', name: 'Testosterone – Total', price: 700 },
    { code: 'HOR-TSTF', name: 'Free Testosterone', price: 1000 },
    { code: 'HOR-E2', name: 'Estradiol / E2', price: 700 },
    { code: 'HOR-PROG', name: 'Progesterone', price: 700 },
    { code: 'HOR-LH', name: 'LH', price: 500 },
    { code: 'HOR-FSH', name: 'FSH', price: 500 },
    { code: 'HOR-PRL', name: 'Prolactin', price: 500 },
    { code: 'HOR-AMH', name: 'AMH', price: 1500 },
    { code: 'HOR-DHEAS', name: 'DHEA-S', price: 900 },
    { code: 'HOR-CORT', name: 'Cortisol', price: 600 },
    { code: 'HOR-ACTH', name: 'ACTH', price: 1000 },
    { code: 'HOR-GH', name: 'Growth Hormone', price: 1000 },
    { code: 'HOR-INS', name: 'Insulin', price: 500 },
    { code: 'HOR-CPEP', name: 'C-Peptide', price: 800 },
    { code: 'HOR-PTH', name: 'PTH', price: 900 },
  ],
  'Pregnancy & Fertility': [
    { code: 'PREG-UPT', name: 'Urine Pregnancy Test', price: 150 },
    { code: 'PREG-SBHCG', name: 'Serum Beta-HCG', price: 500 },
    { code: 'PREG-QBHCG', name: 'Quantitative Beta-HCG', price: 600 },
    { code: 'PREG-AMH', name: 'AMH', price: 1500 },
    { code: 'PREG-SA', name: 'Semen Analysis', price: 300 },
    { code: 'PREG-SCUL', name: 'Semen Culture', price: 700 },
    { code: 'PREG-PRL', name: 'Prolactin', price: 500 },
    { code: 'PREG-FSH', name: 'FSH', price: 500 },
    { code: 'PREG-LH', name: 'LH', price: 500 },
    { code: 'PREG-PROG', name: 'Progesterone', price: 700 },
    { code: 'PREG-E2', name: 'Estradiol', price: 700 },
  ],
  "Men's Health": [
    { code: 'MEN-PSAT', name: 'PSA Total', price: 600 },
    { code: 'MEN-PSAF', name: 'Free PSA', price: 900 },
    { code: 'MEN-PSAR', name: 'PSA Ratio', price: 900 },
    { code: 'MEN-TST', name: 'Testosterone', price: 700 },
    { code: 'MEN-TSTF', name: 'Free Testosterone', price: 1000 },
    { code: 'MEN-SA', name: 'Semen Analysis', price: 300 },
    { code: 'MEN-SCUL', name: 'Semen Culture', price: 700 },
    { code: 'MEN-DHEAS', name: 'DHEA-S', price: 900 },
  ],
  Cardiac: [
    { code: 'CAR-TROPI', name: 'Troponin-I', price: 800 },
    { code: 'CAR-TROPT', name: 'Troponin-T', price: 800 },
    { code: 'CAR-CKMB', name: 'CK-MB', price: 500 },
    { code: 'CAR-CPK', name: 'CPK', price: 400 },
    { code: 'CAR-BNP', name: 'BNP', price: 2000 },
    { code: 'CAR-NTBNP', name: 'NT-proBNP', price: 2000 },
    { code: 'CAR-HSCRP', name: 'hs-CRP', price: 600 },
    { code: 'CAR-HCY', name: 'Homocysteine', price: 900 },
  ],
  'Tumor Markers': [
    { code: 'TUM-AFP', name: 'AFP', price: 700 },
    { code: 'TUM-CEA', name: 'CEA', price: 900 },
    { code: 'TUM-CA125', name: 'CA-125', price: 1000 },
    { code: 'TUM-CA153', name: 'CA 15-3', price: 1000 },
    { code: 'TUM-CA199', name: 'CA 19-9', price: 1000 },
    { code: 'TUM-PSA', name: 'PSA', price: 600 },
    { code: 'TUM-FPSA', name: 'Free PSA', price: 900 },
    { code: 'TUM-BHCG', name: 'Beta-HCG', price: 500 },
    { code: 'TUM-CALC', name: 'Calcitonin', price: 1200 },
    { code: 'TUM-TG', name: 'Thyroglobulin', price: 900 },
  ],
  Microbiology: [
    { code: 'MIC-BCUL', name: 'Blood Culture', price: 1200 },
    { code: 'MIC-UCUL', name: 'Urine Culture', price: 700 },
    { code: 'MIC-SCUL', name: 'Stool Culture', price: 700 },
    { code: 'MIC-SPCUL', name: 'Sputum Culture', price: 700 },
    { code: 'MIC-THCUL', name: 'Throat Swab Culture', price: 600 },
    { code: 'MIC-PCUL', name: 'Pus Culture', price: 700 },
    { code: 'MIC-WCUL', name: 'Wound Culture', price: 700 },
    { code: 'MIC-AFB', name: 'AFB Smear', price: 300 },
    { code: 'MIC-GRAM', name: 'Gram Stain', price: 250 },
    { code: 'MIC-KOH', name: 'KOH Mount', price: 250 },
    { code: 'MIC-FCUL', name: 'Fungal Culture', price: 900 },
  ],
  'Molecular / PCR': [
    { code: 'PCR-COV', name: 'COVID-19 RT-PCR', price: 800 },
    { code: 'PCR-INF', name: 'Influenza A/B PCR', price: 1500 },
    { code: 'PCR-DENG', name: 'Dengue PCR', price: 1500 },
    { code: 'PCR-TB', name: 'TB PCR / CBNAAT', price: 2000 },
    { code: 'PCR-HPV', name: 'HPV DNA PCR', price: 2000 },
    { code: 'PCR-HCV', name: 'HCV RNA PCR', price: 2500 },
    { code: 'PCR-HBV', name: 'HBV DNA PCR', price: 2500 },
    { code: 'PCR-HIV', name: 'HIV Viral Load', price: 2500 },
    { code: 'PCR-CHL', name: 'Chlamydia PCR', price: 1500 },
    { code: 'PCR-GON', name: 'Gonorrhea PCR', price: 1500 },
  ],
  'Allergy & Autoimmune': [
    { code: 'ALL-IGE', name: 'Total IgE', price: 700 },
    { code: 'ALL-IGG', name: 'IgG', price: 600 },
    { code: 'ALL-IGA', name: 'IgA', price: 600 },
    { code: 'ALL-IGM', name: 'IgM', price: 600 },
    { code: 'ALL-IGG4', name: 'IgG4', price: 1000 },
    { code: 'ALL-ANA', name: 'ANA', price: 800 },
    { code: 'ALL-ANAP', name: 'ANA Profile', price: 2000 },
    { code: 'ALL-DSDNA', name: 'Anti-dsDNA', price: 900 },
    { code: 'ALL-C3', name: 'C3 Complement', price: 600 },
    { code: 'ALL-C4', name: 'C4 Complement', price: 600 },
    { code: 'ALL-RF', name: 'Rheumatoid Factor', price: 400 },
    { code: 'ALL-CCP', name: 'Anti-CCP', price: 900 },
    { code: 'ALL-ASO', name: 'ASO', price: 350 },
    { code: 'ALL-CRP', name: 'CRP', price: 300 },
  ],
  Coagulation: [
    { code: 'COA-PT', name: 'PT / Prothrombin Time', price: 300 },
    { code: 'COA-INR', name: 'INR', price: 250 },
    { code: 'COA-APTT', name: 'APTT', price: 350 },
    { code: 'COA-DDIMER', name: 'D-Dimer', price: 800 },
    { code: 'COA-FIB', name: 'Fibrinogen', price: 700 },
    { code: 'COA-BT', name: 'Bleeding Time', price: 100 },
    { code: 'COA-CT', name: 'Clotting Time', price: 100 },
  ],
  Electrolytes: [
    { code: 'ELE-NA', name: 'Sodium', price: 200 },
    { code: 'ELE-K', name: 'Potassium', price: 200 },
    { code: 'ELE-CL', name: 'Chloride', price: 200 },
    { code: 'ELE-CA', name: 'Calcium', price: 200 },
    { code: 'ELE-MG', name: 'Magnesium', price: 300 },
    { code: 'ELE-PHOS', name: 'Phosphorus', price: 200 },
    { code: 'ELE-PANEL', name: 'Electrolyte Panel', price: 600 },
  ],
};

export const seedLabCatalogue = async () => {
  console.log('🧪 Seeding Master Lab Test Catalogue...');

  // Clear existing
  await prisma.labTestCatalog.deleteMany().catch(() => {});
  await prisma.masterLabTest.deleteMany().catch(() => {});
  await prisma.masterLabCategory.deleteMany().catch(() => {});

  const hospitals = await prisma.hospital.findMany();

  for (const [categoryName, tests] of Object.entries(labCategories)) {
    const category = await prisma.masterLabCategory.create({
      data: { name: categoryName },
    });

    for (const test of tests) {
      const masterTest = await prisma.masterLabTest.create({
        data: {
          code: test.code,
          name: test.name,
          basePrice: test.price,
          categoryId: category.id,
        },
      });

      // Auto-assign to all hospitals
      for (const hospital of hospitals) {
        await prisma.labTestCatalog.create({
          data: {
            hospitalId: hospital.id,
            masterTestId: masterTest.id,
            name: test.name,
            price: test.price,
            isActive: true,
          },
        });
      }
    }
  }

  console.log('✅ Master Lab Test Catalogue successfully seeded to all hospitals.');
};
