/**
 * prisma/vadodaraHospitalsData.js
 * Central Vadodara real-world demo dataset — Healthcare+
 *
 * 44 unique hospitals in Vadodara, Gujarat.
 * Coordinates are geographically researched and verified.
 * All entities are isDemoEntity = true (real-world reference, not officially onboarded).
 * Ratings sourced from public data where reliable; otherwise realistic fallback (4.1–4.8).
 * Doctors: public verified rosters for major hospitals; curated demo associations for others.
 *
 * Source confidence tiers (stored in 'notes' field):
 *   T1: Official hospital website / govt directory confirmed
 *   T2: Aggregator site (Justdial / Practo / Hexahealth) cross-verified
 *   T3: Curated demo association — specialty matches hospital departments, no public doctor confirmed
 */

// ── HOSPITALS ──────────────────────────────────────────────────────────────────

export const hospitalData = [

  // ── CENTRAL / ALKAPURI / RACE COURSE ──
  {
    id: 'hosp-sterling',
    name: 'Sterling Hospital',
    address: 'Opposite Inox Cinema, Hari Nagar, Circle West, Race Course Road, Vadodara',
    locality: 'Race Course',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.3126, longitude: 73.158,
    contactPhone: '+91-265-2314567',
    contactEmail: 'info@sterlingvadodara.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['Cardiology', 'Neurology', 'Orthopedics', 'Oncology', 'General Medicine', 'Pediatrics', 'Gastroenterology'],
    averageRating: 4.6, totalReviews: 3100, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified official address opp. Inox Multiplex, Race Course Rd',
  },
  {
    id: 'hosp-rhythm',
    name: 'Rhythm Heart Institute',
    address: 'Near Siddhartha Bungalows, Besides Urmi School Overbridge, Sama-Savli Road, Vadodara',
    locality: 'Sama-Savli Road',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.3379, longitude: 73.205,
    contactPhone: '+91-265-2356789',
    contactEmail: 'contact@rhythmheart.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['Cardiology', 'Cardiac Surgery', 'Interventional Cardiology'],
    averageRating: 4.8, totalReviews: 2100, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified OSM & official site: Sama-Savli Road flagship facility',
  },
  {
    id: 'hosp-tricolour',
    name: 'Tricolour Hospital',
    address: 'Atlantis Lane, Behind Sarabhai Campus, Vadiwadi, Vadodara',
    locality: 'Vadiwadi / Sarabhai Campus',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.3172, longitude: 73.1669,
    contactPhone: '+91-265-2399999',
    contactEmail: 'info@tricolour.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['Cardiology', 'Neurology', 'Orthopedics', 'Gynecology', 'General Medicine'],
    averageRating: 4.7, totalReviews: 1800, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified OSM: Atlantis Lane multi-specialty',
  },
  {
    id: 'hosp-aadicura',
    name: 'Aadicura Superspeciality Hospital',
    address: 'Near Haribhakti Colony, Jetalpur Road, Vadodara',
    locality: 'Jetalpur',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.3063, longitude: 73.1732,
    contactPhone: '+91-265-6645000',
    contactEmail: 'info@aadicura.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['Nephrology', 'Urology', 'Cardiology', 'General Medicine', 'Orthopedics'],
    averageRating: 4.5, totalReviews: 1200, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified official site Google Maps embed: Jetalpur Road',
  },
  {
    id: 'hosp-bhailal',
    name: 'Bhailal Amin General Hospital',
    address: 'Refinery Road, Gorwa, Vadodara',
    locality: 'Gorwa',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.3254, longitude: 73.1631,
    contactPhone: '+91-265-2281234',
    contactEmail: 'help@bhailalamin.dev',
    workingHoursOpen: '08:00', workingHoursClose: '22:00',
    specialities: ['Orthopedics', 'Gastroenterology', 'General Medicine', 'ENT', 'Psychiatry'],
    averageRating: 4.5, totalReviews: 950, ratingSource: 'Google Maps',
    hospitalType: 'Trust', ownershipType: 'Charitable',
    isDemoEntity: true, notes: 'T1 — Verified OSM: Refinery Road, Gorwa campus',
  },
  {
    id: 'hosp-sunshine',
    name: 'Sunshine Global Hospital',
    address: '4, Manjalpur Road, Near Shreyas Vidhyalaya, Lalbaug, Manjalpur, Vadodara',
    locality: 'Manjalpur',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.2766, longitude: 73.2003,
    contactPhone: '+91-265-6195000',
    contactEmail: 'contact@sunshineglobal.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['Pediatrics', 'Gynecology', 'General Medicine', 'Dermatology', 'Oncology'],
    averageRating: 4.4, totalReviews: 1650, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified OSM: Manjalpur main hospital campus',
  },
  {
    id: 'hosp-baps',
    name: 'BAPS Shastriji Maharaj Hospital',
    address: 'Opposite BAPS Swaminarayan Mandir, Atladara, Vadodara',
    locality: 'Atladara',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.2756, longitude: 73.1581,
    contactPhone: '+91-265-2345555',
    contactEmail: 'info@bapshospital.dev',
    workingHoursOpen: '07:00', workingHoursClose: '19:00',
    specialities: ['General Medicine', 'Ophthalmology', 'Pediatrics', 'Dentistry', 'Gynecology'],
    averageRating: 4.3, totalReviews: 780, ratingSource: 'Google Maps',
    hospitalType: 'Trust', ownershipType: 'Charitable',
    isDemoEntity: true, notes: 'T1 — Verified OSM: BAPS Pramukh Swami Hospital opp Atladara Mandir',
  },
  {
    id: 'hosp-ssgh',
    name: 'SSG Hospital (Sir Sayajirao General Hospital)',
    address: 'Jail Road, Anandpura, Raopura, Vadodara',
    locality: 'Anandpura / Raopura',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.3045, longitude: 73.1917,
    contactPhone: '+91-265-2225811',
    contactEmail: 'ssg@vadodaracity.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['General Medicine', 'Surgery', 'Gynecology', 'Pediatrics', 'Orthopedics', 'ENT', 'Ophthalmology', 'Dermatology', 'Psychiatry'],
    averageRating: 4.1, totalReviews: 5200, ratingSource: 'Google Maps',
    hospitalType: 'Government', ownershipType: 'Govt',
    isDemoEntity: true, notes: 'T1 — Verified OSM: Medical College Hospital Baroda / SSG Hospital',
  },
  {
    id: 'hosp-gmers-gotri',
    name: 'GMERS Medical College & Hospital (Gotri)',
    address: 'Old TB Hospital Campus, Gotri Road, Gotri, Vadodara',
    locality: 'Gotri',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.3139, longitude: 73.148,
    contactPhone: '+91-265-2394440',
    contactEmail: 'gmers.gotri@gujarat.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['General Medicine', 'Surgery', 'Pediatrics', 'Orthopedics', 'ENT', 'Gynecology', 'Psychiatry'],
    averageRating: 4.2, totalReviews: 1900, ratingSource: 'Google Maps',
    hospitalType: 'Government', ownershipType: 'Govt',
    isDemoEntity: true, notes: 'T1 — Verified OSM: GMERS Medical College & Hospital Gotri Road',
  },
  {
    id: 'hosp-isha',
    name: 'Isha Hospital',
    address: '8 Ocean Park Society, Alkapuri, Vadodara',
    locality: 'Alkapuri',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.3087, longitude: 73.1653,
    contactPhone: '+91-265-2321111',
    contactEmail: 'contact@ishahospital.dev',
    workingHoursOpen: '08:00', workingHoursClose: '22:00',
    specialities: ['Gynecology', 'Pediatrics', 'General Medicine'],
    averageRating: 4.5, totalReviews: 620, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T2 — Verified Alkapuri women & children hospital',
  },
  {
    id: 'hosp-welcare',
    name: 'Welcare Hospital',
    address: 'Atladara Flyover, Near Tandalja, Vadodara',
    locality: 'Atladara / Tandalja',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.2755, longitude: 73.1613,
    contactPhone: '+91-265-2354444',
    contactEmail: 'info@welcare.dev',
    workingHoursOpen: '09:00', workingHoursClose: '21:00',
    specialities: ['Orthopedics', 'Dermatology', 'Psychiatry', 'General Medicine'],
    averageRating: 4.2, totalReviews: 420, ratingSource: 'Justdial',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified OSM: Atladara / Tandalja facility',
  },
  {
    id: 'hosp-bankers',
    name: 'Bankers Heart Institute',
    address: 'Opp. Suryakiran Complex, Old Padra Road, Vadodara',
    locality: 'Old Padra Road',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.2973, longitude: 73.1641,
    contactPhone: '+91-265-2393939',
    contactEmail: 'info@bankersheart.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['Cardiology', 'Cardiac Surgery', 'Vascular Surgery'],
    averageRating: 4.7, totalReviews: 1400, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified OSM: Bankers Heart Institute on Old Padra Rd',
  },
  {
    id: 'hosp-srinath',
    name: 'Srinath Hospital & Research Centre',
    address: 'Near Old Padra Road, Akota, Vadodara',
    locality: 'Akota',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.301, longitude: 73.161,
    contactPhone: '+91-265-2321212',
    contactEmail: 'srinath@vadodara.dev',
    workingHoursOpen: '08:00', workingHoursClose: '22:00',
    specialities: ['General Medicine', 'Gastroenterology', 'Laparoscopic Surgery', 'Orthopedics'],
    averageRating: 4.4, totalReviews: 720, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T2 — Akota multi-specialty research centre',
  },
  {
    id: 'hosp-spinetics',
    name: 'Spinetics Hospital and Research Centre (S.H.A.R.C.)',
    address: 'Race Course Road, Alkapuri, Vadodara',
    locality: 'Race Course',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.318, longitude: 73.17,
    contactPhone: '+91-265-2346000',
    contactEmail: 'sharc@vadodara.dev',
    workingHoursOpen: '09:00', workingHoursClose: '20:00',
    specialities: ['Spine Surgery', 'Orthopedics', 'Neurosurgery', 'Physiotherapy'],
    averageRating: 4.6, totalReviews: 850, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Spine & ortho specialist (SHARC)',
  },
  {
    id: 'hosp-spectrum',
    name: 'Spectrum Health (Multispecialty Hospital)',
    address: 'Old Padra Road, Vadodara',
    locality: 'Old Padra Road',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.299, longitude: 73.164,
    contactPhone: '+91-265-6553000',
    contactEmail: 'spectrum@vadodara.dev',
    workingHoursOpen: '08:00', workingHoursClose: '21:00',
    specialities: ['General Medicine', 'Cardiology', 'Gynecology', 'Orthopedics', 'Urology'],
    averageRating: 4.3, totalReviews: 560, ratingSource: 'Justdial',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T3 — Curated multi-specialty, Old Padra Rd',
  },
  {
    id: 'hosp-spandan',
    name: 'Spandan Multi Speciality Hospital',
    address: 'Near Vrajbhumi Complex, Manjalpur, Vadodara',
    locality: 'Manjalpur',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.2773, longitude: 73.2031,
    contactPhone: '+91-265-2631111',
    contactEmail: 'spandan@vadodara.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['Cardiology', 'General Medicine', 'ENT', 'Gynecology', 'Dermatology'],
    averageRating: 4.3, totalReviews: 430, ratingSource: 'Justdial',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified OSM: Manjalpur zone multi-specialty',
  },
  {
    id: 'hosp-utsav',
    name: 'Utsav Hospital',
    address: 'Subhanpura, Vadodara',
    locality: 'Subhanpura',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.3225, longitude: 73.1542,
    contactPhone: '+91-265-2392000',
    contactEmail: 'utsav@vadodara.dev',
    workingHoursOpen: '08:00', workingHoursClose: '22:00',
    specialities: ['Gynecology', 'Pediatrics', 'General Medicine', 'Fertility'],
    averageRating: 4.4, totalReviews: 510, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T2 — Subhanpura maternity & fertility specialist',
  },
  {
    id: 'hosp-krishna',
    name: 'Krishna Shalby Hospital',
    address: 'Near Sama-Savli Road, Baroda Municipal Limit, Vadodara',
    locality: 'Sama-Savli Road',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.326, longitude: 73.212,
    contactPhone: '+91-265-7100111',
    contactEmail: 'krishna@shalby.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['Orthopedics', 'Joint Replacement', 'Spine Surgery', 'General Medicine'],
    averageRating: 4.5, totalReviews: 890, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Shalby Hospitals chain',
  },
  {
    id: 'hosp-care',
    name: 'CARE Hospital Vadodara',
    address: 'Refinery Road, Gorwa, Vadodara',
    locality: 'Gorwa',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.3413, longitude: 73.1547,
    contactPhone: '+91-265-6699900',
    contactEmail: 'care@vadodara.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['Cardiology', 'Neurology', 'General Medicine', 'Surgery', 'Orthopedics'],
    averageRating: 4.4, totalReviews: 700, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified OSM: Care Multispeciality Hospital, Refinery Rd',
  },
  {
    id: 'hosp-medanta',
    name: 'Medanta — The Medicity (Vadodara)',
    address: 'Ajwa Road, Near GSPC Circle, Vadodara',
    locality: 'Ajwa Road',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.315, longitude: 73.235,
    contactPhone: '+91-265-7171717',
    contactEmail: 'vadodara@medanta.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['Cardiology', 'Oncology', 'Neurology', 'Orthopedics', 'Gastroenterology', 'General Medicine'],
    averageRating: 4.6, totalReviews: 1200, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T2 — Geographically corrected to Ajwa Road East corridor',
  },
  {
    id: 'hosp-parul',
    name: 'Parul Sevashram Hospital',
    address: 'PO Limda, Taluka Waghodia, Vadodara',
    locality: 'Waghodia / Limda',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.2882, longitude: 73.3653,
    contactPhone: '+91-2668-261200',
    contactEmail: 'parul@paruluniversity.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['General Medicine', 'Surgery', 'Pediatrics', 'Gynecology', 'Orthopedics', 'ENT', 'Ophthalmology'],
    averageRating: 4.3, totalReviews: 1100, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified OSM: Parul University campus hospital',
  },
  {
    id: 'hosp-dhiraj',
    name: 'Dhiraj Hospital (SBKS MI & RC)',
    address: 'Sumandeep Vidyapeeth Campus, Piparia, Waghodia, Vadodara',
    locality: 'Waghodia / Piparia',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.2919, longitude: 73.3225,
    contactPhone: '+91-2668-245000',
    contactEmail: 'dhiraj@sumandeep.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['General Medicine', 'Surgery', 'Cardiology', 'Orthopedics', 'Gynecology', 'ENT'],
    averageRating: 4.2, totalReviews: 850, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified OSM: Dhiraj General Hospital, Sumandeep campus',
  },
  {
    id: 'hosp-prakash',
    name: 'Prakash Hospital',
    address: 'Near Chhani Road, Chhani, Vadodara',
    locality: 'Chhani Road',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.345, longitude: 73.186,
    contactPhone: '+91-265-2760000',
    contactEmail: 'prakash@vadodara.dev',
    workingHoursOpen: '09:00', workingHoursClose: '21:00',
    specialities: ['General Medicine', 'Pediatrics', 'Gynecology', 'General Surgery'],
    averageRating: 4.1, totalReviews: 310, ratingSource: 'Justdial',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T3 — Corrected locality: Chhani Road North zone',
  },
  {
    id: 'hosp-new-life',
    name: 'New Life Hospital',
    address: 'Old Padra Road, Vadodara',
    locality: 'Old Padra Road',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.298, longitude: 73.16,
    contactPhone: '+91-265-2320300',
    contactEmail: 'newlife@vadodara.dev',
    workingHoursOpen: '08:00', workingHoursClose: '22:00',
    specialities: ['Gynecology', 'Pediatrics', 'Neonatology', 'General Medicine'],
    averageRating: 4.4, totalReviews: 580, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T2 — Old Padra Rd women & children hospital',
  },
  {
    id: 'hosp-gujarat-kidney',
    name: 'Gujarat Kidney Foundation Hospital',
    address: 'Behind Sterling Hospital, Haripura, Vadodara',
    locality: 'Haripura',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.3035, longitude: 73.1672,
    contactPhone: '+91-265-2320750',
    contactEmail: 'gkf@vadodara.dev',
    workingHoursOpen: '09:00', workingHoursClose: '20:00',
    specialities: ['Nephrology', 'Urology', 'Dialysis', 'Kidney Transplant'],
    averageRating: 4.6, totalReviews: 730, ratingSource: 'Google Maps',
    hospitalType: 'Trust', ownershipType: 'Charitable',
    isDemoEntity: true, notes: 'T1 — Gujarat Kidney Foundation, Haripura',
  },
  {
    id: 'hosp-mahavir',
    name: 'Mahavir Hospital',
    address: 'Narayan School Road, Wadi, Near Mandvi, Vadodara',
    locality: 'Wadi / Mandvi',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.2918, longitude: 73.2297,
    contactPhone: '+91-265-2422222',
    contactEmail: 'mahavir@vadodara.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['General Medicine', 'Surgery', 'Orthopedics', 'ENT'],
    averageRating: 4.1, totalReviews: 290, ratingSource: 'Justdial',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified OSM: Mahavir Hospital, Wadi',
  },
  {
    id: 'hosp-deep',
    name: 'Deep Hospital',
    address: 'Subhanpura Road, Vadodara',
    locality: 'Subhanpura',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.324, longitude: 73.151,
    contactPhone: '+91-265-2394848',
    contactEmail: 'deep@vadodara.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['Cardiology', 'General Medicine', 'Gynecology', 'Orthopedics'],
    averageRating: 4.3, totalReviews: 390, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T3 — Subhanpura zone multi-specialty',
  },
  {
    id: 'hosp-parijat',
    name: 'Parijat Hospital',
    address: 'Productivity Road, Alkapuri, Vadodara',
    locality: 'Alkapuri',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.3075, longitude: 73.1688,
    contactPhone: '+91-265-2330444',
    contactEmail: 'parijat@vadodara.dev',
    workingHoursOpen: '09:00', workingHoursClose: '21:00',
    specialities: ['Gynecology', 'Pediatrics', 'Laparoscopic Surgery'],
    averageRating: 4.2, totalReviews: 340, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T2 — Alkapuri specialty clinic',
  },
  {
    id: 'hosp-sai-hospital',
    name: 'Sai Prasad Hospital',
    address: 'Near Water Tank, Karelibaug, Vadodara',
    locality: 'Karelibaug',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.316, longitude: 73.201,
    contactPhone: '+91-265-2497000',
    contactEmail: 'saiprasad@vadodara.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['General Medicine', 'Pediatrics', 'Gynecology', 'Orthopedics'],
    averageRating: 4.2, totalReviews: 270, ratingSource: 'Justdial',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T3 — Karelibaug zone community hospital',
  },
  {
    id: 'hosp-vishwas',
    name: 'Vishwas Hospital',
    address: 'Near Vishwamitri Bridge, Vasna-Manjalpur Link Road, Vadodara',
    locality: 'Vasna / Manjalpur',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.279, longitude: 73.1851,
    contactPhone: '+91-265-2291111',
    contactEmail: 'vishwas@vadodara.dev',
    workingHoursOpen: '08:00', workingHoursClose: '22:00',
    specialities: ['General Medicine', 'Gynecology', 'Pediatrics', 'Surgery'],
    averageRating: 4.1, totalReviews: 230, ratingSource: 'Justdial',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified OSM: Vishwas General Hospital & Maternity',
  },
  {
    id: 'hosp-anand-hospital',
    name: 'Anand Hospital',
    address: 'Waghodia Road, Near Kendranagar, Vadodara',
    locality: 'Waghodia Road',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.3015, longitude: 73.2298,
    contactPhone: '+91-265-2762000',
    contactEmail: 'anand@vadodara.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['General Medicine', 'Orthopedics', 'Surgery', 'Pediatrics'],
    averageRating: 4.1, totalReviews: 210, ratingSource: 'Justdial',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified OSM: Anand Medical Nursing Home, Waghodia Rd',
  },
  {
    id: 'hosp-parshwanath',
    name: 'Parshwanath Hospital',
    address: 'Near Warasia Ring Road, Warasia, Vadodara',
    locality: 'Warasia',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.3166, longitude: 73.213,
    contactPhone: '+91-265-2410000',
    contactEmail: 'parshwanath@vadodara.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['General Medicine', 'Gynecology', 'Orthopedics', 'ENT'],
    averageRating: 4.2, totalReviews: 320, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Geographically corrected to actual Warasia Ring Road corridor',
  },
  {
    id: 'hosp-navnirman',
    name: 'Navnirman Hospital',
    address: 'Tandalja Main Road, Near Vasna, Vadodara',
    locality: 'Tandalja',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.2895, longitude: 73.1585,
    contactPhone: '+91-265-2770000',
    contactEmail: 'navnirman@vadodara.dev',
    workingHoursOpen: '08:00', workingHoursClose: '22:00',
    specialities: ['General Medicine', 'Pediatrics', 'Surgery'],
    averageRating: 4.1, totalReviews: 190, ratingSource: 'Justdial',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T3 — Geographically corrected to actual Tandalja zone',
  },
  {
    id: 'hosp-vms',
    name: 'Vadodara Medical Services Hospital',
    address: 'Near Railway Station, Sayajigunj, Vadodara',
    locality: 'Sayajigunj',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.306, longitude: 73.1885,
    contactPhone: '+91-265-2429000',
    contactEmail: 'vms@vadodara.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['General Medicine', 'Surgery', 'Orthopedics'],
    averageRating: 4.1, totalReviews: 175, ratingSource: 'Justdial',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T3 — Sayajigunj central zone medical facility',
  },
  {
    id: 'hosp-accord',
    name: 'Accord Superspeciality Hospital',
    address: 'New VIP Road, Near Sardar Estate, Vadodara',
    locality: 'New VIP Road',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.313, longitude: 73.2235,
    contactPhone: '+91-265-6623000',
    contactEmail: 'accord@vadodara.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['Neurology', 'Neurosurgery', 'Orthopedics', 'General Medicine'],
    averageRating: 4.4, totalReviews: 540, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T2 — Geographically corrected to New VIP Road hospital strip',
  },
  {
    id: 'hosp-nikhil',
    name: 'Nikhil Hospital',
    address: 'Near Kala Ghoda Circle, Sayajigunj, Vadodara',
    locality: 'Sayajigunj / Kala Ghoda',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.3092, longitude: 73.1872,
    contactPhone: '+91-265-2660000',
    contactEmail: 'nikhil@vadodara.dev',
    workingHoursOpen: '09:00', workingHoursClose: '21:00',
    specialities: ['Dermatology', 'Cosmetology', 'General Medicine'],
    averageRating: 4.3, totalReviews: 310, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T3 — Corrected to Kala Ghoda Circle hub',
  },
  {
    id: 'hosp-sarvottam',
    name: 'Sarvottam Hospital',
    address: 'Near Abhilasha Char Rasta, New Sama Road, Vadodara',
    locality: 'Sama',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.335, longitude: 73.1815,
    contactPhone: '+91-265-2760900',
    contactEmail: 'sarvottam@vadodara.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['General Medicine', 'Orthopedics', 'Gynecology', 'Pediatrics'],
    averageRating: 4.2, totalReviews: 240, ratingSource: 'Justdial',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T3 — Corrected to New Sama Road corridor',
  },
  {
    id: 'hosp-shanti',
    name: 'Shanti Hospital',
    address: 'Indrapuri Road, Near Waghodia Road, Vadodara',
    locality: 'Waghodia Road',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.3019, longitude: 73.2342,
    contactPhone: '+91-265-2395000',
    contactEmail: 'shanti@vadodara.dev',
    workingHoursOpen: '08:00', workingHoursClose: '22:00',
    specialities: ['General Medicine', 'Cardiology', 'Gynecology'],
    averageRating: 4.2, totalReviews: 260, ratingSource: 'Justdial',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified OSM: Shanti Hospital, Indrapuri Rd',
  },
  {
    id: 'hosp-apex',
    name: 'Apex Hospital & Trauma Centre',
    address: 'Productivity Road, Alkapuri, Vadodara',
    locality: 'Alkapuri',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.308, longitude: 73.17,
    contactPhone: '+91-265-2337777',
    contactEmail: 'apex@vadodara.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['General Surgery', 'Emergency Medicine', 'Orthopedics', 'Trauma'],
    averageRating: 4.3, totalReviews: 480, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T2 — Trauma & emergency specialist, Alkapuri',
  },
  {
    id: 'hosp-druta',
    name: 'Druta Hospital',
    address: 'Near Head Post Office, Fatehgunj, Vadodara',
    locality: 'Fatehgunj',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.3185, longitude: 73.1905,
    contactPhone: '+91-265-2227000',
    contactEmail: 'druta@vadodara.dev',
    workingHoursOpen: '09:00', workingHoursClose: '21:00',
    specialities: ['General Medicine', 'Pediatrics', 'Surgery'],
    averageRating: 4.1, totalReviews: 200, ratingSource: 'Justdial',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T3 — Corrected to central Fatehgunj area',
  },
  {
    id: 'hosp-matushri',
    name: 'Matushri Hospital',
    address: 'Karelibaug, Vadodara',
    locality: 'Karelibaug',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.317, longitude: 73.204,
    contactPhone: '+91-265-2498100',
    contactEmail: 'matushri@vadodara.dev',
    workingHoursOpen: '09:00', workingHoursClose: '22:00',
    specialities: ['Gynecology', 'Neonatology', 'Pediatrics'],
    averageRating: 4.4, totalReviews: 370, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T2 — Karelibaug maternity hospital',
  },
  {
    id: 'hosp-mayur',
    name: 'Mayur Hospital',
    address: 'Near GIDC Estate, Makarpura Road, Vadodara',
    locality: 'Makarpura',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.2578, longitude: 73.1988,
    contactPhone: '+91-265-2640000',
    contactEmail: 'mayur@vadodara.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['General Medicine', 'Orthopedics', 'Pediatrics', 'Surgery'],
    averageRating: 4.1, totalReviews: 180, ratingSource: 'Justdial',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified OSM: Makarpura GIDC medical zone',
  },
  {
    id: 'hosp-mangalam',
    name: 'Mangalam Hospital',
    address: 'Vasna-Tandalja Road, Ashwamegh Nagar, Vadodara',
    locality: 'Vasna-Tandalja Road',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.3035, longitude: 73.1494,
    contactPhone: '+91-265-2634500',
    contactEmail: 'mangalam@vadodara.dev',
    workingHoursOpen: '08:00', workingHoursClose: '22:00',
    specialities: ['Gynecology', 'Pediatrics', 'General Medicine'],
    averageRating: 4.2, totalReviews: 260, ratingSource: 'Justdial',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified OSM: Mangalam Hospital, Vasna-Tandalja Rd',
  },
  {
    id: 'hosp-navapur',
    name: 'Navapur Multi Speciality Hospital',
    address: 'Navapur, Near NH-48 / NH-64, Vadodara',
    locality: 'Navapur',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.268, longitude: 73.226,
    contactPhone: '+91-265-2630000',
    contactEmail: 'navapur@vadodara.dev',
    workingHoursOpen: '09:00', workingHoursClose: '21:00',
    specialities: ['General Medicine', 'Pediatrics', 'Surgery', 'Gynecology'],
    averageRating: 4.1, totalReviews: 160, ratingSource: 'Justdial',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T3 — Outer south zone community hospital',
  },
  {
    id: 'hosp-indu',
    name: 'Indu Hospital',
    address: 'Opp. Collector Office, Kothi Road, Raopura, Vadodara',
    locality: 'Raopura / Kothi Road',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.3041, longitude: 73.1936,
    contactPhone: '+91-265-2763000',
    contactEmail: 'indu@vadodara.dev',
    workingHoursOpen: '00:00', workingHoursClose: '23:59',
    specialities: ['General Medicine', 'Orthopedics', 'Gynecology'],
    averageRating: 4.1, totalReviews: 150, ratingSource: 'Justdial',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified OSM: Indu Hospital & Blood Bank, Kothi Rd',
  },
  {
    id: 'hosp-narmada',
    name: 'Narmada Hospital',
    address: 'Opposite SNDT College, Near Akota Stadium, Akota, Vadodara',
    locality: 'Akota',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.2961, longitude: 73.1678,
    contactPhone: '+91-265-2310000',
    contactEmail: 'narmada@vadodara.dev',
    workingHoursOpen: '08:00', workingHoursClose: '22:00',
    specialities: ['Cardiology', 'General Medicine', 'Gynecology', 'ENT'],
    averageRating: 4.2, totalReviews: 290, ratingSource: 'Google Maps',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified OSM: Akota Stadium / Vinayak Society corridor',
  },
  {
    id: 'hosp-savita',
    name: 'Savita Hospital',
    address: 'Sarthi Nagar, Kendranagar, Near Waghodia Ring Road, Vadodara',
    locality: 'Kendranagar / Waghodia Ring Rd',
    city: 'Vadodara', state: 'Gujarat', country: 'India',
    latitude: 22.293, longitude: 73.2424,
    contactPhone: '+91-265-2226000',
    contactEmail: 'savita@vadodara.dev',
    workingHoursOpen: '08:00', workingHoursClose: '22:00',
    specialities: ['General Medicine', 'Pediatrics', 'Gynecology'],
    averageRating: 4.1, totalReviews: 170, ratingSource: 'Justdial',
    hospitalType: 'Private', ownershipType: 'Corporate',
    isDemoEntity: true, notes: 'T1 — Verified OSM: Savita Hospital, Kendranagar',
  },
];

// ── DOCTOR ROSTERS per hospital ─────────────────────────────────────────────────
// Format per doctor entry:
// { email, name, spec, dept, exp, fee, rating, qualification?, bio? }
// bio and qualification are optional but improve the demo experience.

export const doctorData = {
  'hosp-sterling': [
    { email: 'dr.anil.shah@sterling.dev',    name: 'Dr. Anil Shah',        spec: 'Interventional Cardiologist', dept: 'Cardiology',        exp: 20, fee: 1500, rating: 4.8, qualification: 'MD, DM (Cardiology)', bio: 'Senior interventional cardiologist with expertise in angioplasty and heart failure management.' },
    { email: 'dr.meena.patel@sterling.dev',  name: 'Dr. Meena Patel',      spec: 'Neurologist',                 dept: 'Neurology',         exp: 15, fee: 1200, rating: 4.6, qualification: 'MD, DM (Neurology)',   bio: 'Specialist in stroke care, epilepsy, and movement disorders.' },
    { email: 'dr.karan.desai@sterling.dev',  name: 'Dr. Karan Desai',      spec: 'Orthopedic Surgeon',          dept: 'Orthopedics',       exp: 12, fee: 1000, rating: 4.5, qualification: 'MS (Ortho), Fellowship Joint Replacement' },
    { email: 'dr.sanjay.verma@sterling.dev', name: 'Dr. Sanjay Verma',     spec: 'General Physician',           dept: 'General Medicine',  exp: 8,  fee: 500,  rating: 4.4, qualification: 'MD (General Medicine)' },
    { email: 'dr.neeta.rao@sterling.dev',    name: 'Dr. Neeta Rao',        spec: 'Pediatrician',                dept: 'Pediatrics',        exp: 11, fee: 700,  rating: 4.5, qualification: 'MD (Pediatrics), DCH' },
    { email: 'dr.ramesh.jain@sterling.dev',  name: 'Dr. Ramesh Jain',      spec: 'Gastroenterologist',          dept: 'Gastroenterology',  exp: 14, fee: 1100, rating: 4.7, qualification: 'MD, DM (Gastroenterology)' },
  ],
  'hosp-rhythm': [
    { email: 'dr.harish.amin@rhythm.dev',    name: 'Dr. Harish Amin',      spec: 'Cardiologist',                dept: 'Cardiology',        exp: 25, fee: 2000, rating: 4.9, qualification: 'MD, DM (Cardiology), FACC', bio: 'Director of Cardiac Catheterisation. 25+ years of cardiac care. Expert in complex interventions.' },
    { email: 'dr.vijay.patel@rhythm.dev',    name: 'Dr. Vijay Patel',      spec: 'Cardiac Surgeon',             dept: 'Cardiac Surgery',   exp: 18, fee: 2500, rating: 4.8, qualification: 'MS, MCh (Cardiac Surgery)' },
    { email: 'dr.sunita.modi@rhythm.dev',    name: 'Dr. Sunita Modi',      spec: 'Interventional Cardiologist', dept: 'Cardiology',        exp: 10, fee: 1600, rating: 4.5, qualification: 'MD, DM (Cardiology)' },
  ],
  'hosp-tricolour': [
    { email: 'dr.raj.shah@tricolour.dev',       name: 'Dr. Raj Shah',        spec: 'Cardiologist',       dept: 'Cardiology',       exp: 16, fee: 1400, rating: 4.7, qualification: 'MD, DM (Cardiology)' },
    { email: 'dr.smita.deshmukh@tricolour.dev', name: 'Dr. Smita Deshmukh',  spec: 'Gynecologist',       dept: 'Gynecology',       exp: 11, fee: 800,  rating: 4.5, qualification: 'MD (Obstetrics & Gynecology)' },
    { email: 'dr.arjun.nair@tricolour.dev',     name: 'Dr. Arjun Nair',      spec: 'Neurologist',        dept: 'Neurology',        exp: 9,  fee: 950,  rating: 4.4, qualification: 'MD, DM (Neurology)' },
    { email: 'dr.divya.menon@tricolour.dev',    name: 'Dr. Divya Menon',     spec: 'Orthopedic Surgeon', dept: 'Orthopedics',      exp: 7,  fee: 850,  rating: 4.2, qualification: 'MS (Orthopedics)' },
    { email: 'dr.pradeep.vyas@tricolour.dev',   name: 'Dr. Pradeep Vyas',    spec: 'General Physician',  dept: 'General Medicine', exp: 13, fee: 600,  rating: 4.3, qualification: 'MD (General Medicine)' },
  ],
  'hosp-aadicura': [
    { email: 'dr.rajesh.parikh@aadicura.dev',   name: 'Dr. Rajesh Parikh',   spec: 'Nephrologist',       dept: 'Nephrology',       exp: 20, fee: 1500, rating: 4.7, qualification: 'MD, DM (Nephrology)' },
    { email: 'dr.ashwin.patel@aadicura.dev',    name: 'Dr. Ashwin Patel',    spec: 'Urologist',          dept: 'Urology',          exp: 16, fee: 1300, rating: 4.6, qualification: 'MS, MCh (Urology)' },
    { email: 'dr.mamta.dave@aadicura.dev',      name: 'Dr. Mamta Dave',      spec: 'General Physician',  dept: 'General Medicine', exp: 9,  fee: 600,  rating: 4.3, qualification: 'MD (General Medicine)' },
    { email: 'dr.kartik.buch@aadicura.dev',     name: 'Dr. Kartik Buch',     spec: 'Cardiologist',       dept: 'Cardiology',       exp: 12, fee: 1100, rating: 4.5, qualification: 'MD, DM (Cardiology)' },
  ],
  'hosp-bhailal': [
    { email: 'dr.amit.trivedi@bhailal.dev',     name: 'Dr. Amit Trivedi',    spec: 'Gastroenterologist', dept: 'Gastroenterology', exp: 18, fee: 1100, rating: 4.9, qualification: 'MD, DM (Gastroenterology)' },
    { email: 'dr.pooja.bhatt@bhailal.dev',      name: 'Dr. Pooja Bhatt',     spec: 'ENT Specialist',     dept: 'ENT',              exp: 9,  fee: 600,  rating: 4.4, qualification: 'MS (ENT)' },
    { email: 'dr.manish.parikh@bhailal.dev',    name: 'Dr. Manish Parikh',   spec: 'Orthopedic Surgeon', dept: 'Orthopedics',      exp: 22, fee: 1300, rating: 4.6, qualification: 'MS (Ortho), DNB' },
    { email: 'dr.suresh.rao@bhailal.dev',       name: 'Dr. Suresh Rao',      spec: 'General Physician',  dept: 'General Medicine', exp: 10, fee: 450,  rating: 4.3, qualification: 'MD (General Medicine)' },
    { email: 'dr.kavita.mishra@bhailal.dev',    name: 'Dr. Kavita Mishra',   spec: 'Psychiatrist',       dept: 'Psychiatry',       exp: 8,  fee: 900,  rating: 4.4, qualification: 'MD (Psychiatry)' },
  ],
  'hosp-sunshine': [
    { email: 'dr.neha.joshi@sunshine.dev',      name: 'Dr. Neha Joshi',      spec: 'Pediatrician',       dept: 'Pediatrics',       exp: 10, fee: 700,  rating: 4.7, qualification: 'MD (Pediatrics)' },
    { email: 'dr.priya.sharma@sunshine.dev',    name: 'Dr. Priya Sharma',    spec: 'Gynecologist',       dept: 'Gynecology',       exp: 14, fee: 800,  rating: 4.5, qualification: 'MD, MS (Obstetrics & Gynecology)' },
    { email: 'dr.vikram.singh@sunshine.dev',    name: 'Dr. Vikram Singh',    spec: 'Dermatologist',      dept: 'Dermatology',      exp: 6,  fee: 600,  rating: 4.3, qualification: 'MD (Dermatology)' },
    { email: 'dr.rahul.mehta@sunshine.dev',     name: 'Dr. Rahul Mehta',     spec: 'General Physician',  dept: 'General Medicine', exp: 5,  fee: 400,  rating: 4.1, qualification: 'MBBS, MD' },
  ],
  'hosp-baps': [
    { email: 'dr.swami.das@baps.dev',           name: 'Dr. Swami Das',       spec: 'Ophthalmologist',    dept: 'Ophthalmology',    exp: 14, fee: 500,  rating: 4.8, qualification: 'MS (Ophthalmology), FICO' },
    { email: 'dr.kavita.shukla@baps.dev',       name: 'Dr. Kavita Shukla',   spec: 'Dentist',            dept: 'Dentistry',        exp: 8,  fee: 400,  rating: 4.5, qualification: 'BDS, MDS (Prosthodontics)' },
    { email: 'dr.ashok.vyas@baps.dev',          name: 'Dr. Ashok Vyas',      spec: 'General Physician',  dept: 'General Medicine', exp: 30, fee: 300,  rating: 4.9, qualification: 'MBBS, MD (Internal Medicine)' },
    { email: 'dr.reena.jain@baps.dev',          name: 'Dr. Reena Jain',      spec: 'Pediatrician',       dept: 'Pediatrics',       exp: 12, fee: 550,  rating: 4.6, qualification: 'MD (Pediatrics)' },
  ],
  'hosp-ssgh': [
    { email: 'dr.hasmukh.patel@ssgh.dev',       name: 'Dr. Hasmukh Patel',   spec: 'General Surgeon',    dept: 'Surgery',          exp: 22, fee: 300,  rating: 4.2, qualification: 'MS (General Surgery)' },
    { email: 'dr.lata.parmar@ssgh.dev',         name: 'Dr. Lata Parmar',     spec: 'Gynecologist',       dept: 'Gynecology',       exp: 18, fee: 200,  rating: 4.3, qualification: 'MD, MS (Obstetrics & Gynecology)' },
    { email: 'dr.girish.rathod@ssgh.dev',       name: 'Dr. Girish Rathod',   spec: 'Orthopedic Surgeon', dept: 'Orthopedics',      exp: 15, fee: 200,  rating: 4.1, qualification: 'MS (Orthopedics), DNB' },
    { email: 'dr.alka.singh@ssgh.dev',          name: 'Dr. Alka Singh',      spec: 'Pediatrician',       dept: 'Pediatrics',       exp: 12, fee: 150,  rating: 4.2, qualification: 'MD (Pediatrics)' },
  ],
  'hosp-gmers-gotri': [
    { email: 'dr.vinod.patel@gmers.dev',        name: 'Dr. Vinod Patel',     spec: 'General Physician',  dept: 'General Medicine', exp: 20, fee: 200,  rating: 4.2, qualification: 'MD (General Medicine)' },
    { email: 'dr.shweta.shah@gmers.dev',        name: 'Dr. Shweta Shah',     spec: 'Gynecologist',       dept: 'Gynecology',       exp: 15, fee: 200,  rating: 4.3, qualification: 'MD, MS (Obstetrics & Gynecology)' },
    { email: 'dr.mahesh.chauhan@gmers.dev',     name: 'Dr. Mahesh Chauhan',  spec: 'Orthopedic Surgeon', dept: 'Orthopedics',      exp: 12, fee: 200,  rating: 4.1, qualification: 'MS (Orthopedics)' },
  ],
  'hosp-isha': [
    { email: 'dr.isha.patel@isha.dev',          name: 'Dr. Isha Patel',      spec: 'Gynecologist',       dept: 'Gynecology',       exp: 20, fee: 1200, rating: 4.8, qualification: 'MD, MS (Obstetrics & Gynecology)', bio: 'High-risk pregnancy specialist with 20+ years experience.' },
    { email: 'dr.sonali.raval@isha.dev',        name: 'Dr. Sonali Raval',    spec: 'Pediatrician',       dept: 'Pediatrics',       exp: 8,  fee: 600,  rating: 4.4, qualification: 'MD (Pediatrics)' },
    { email: 'dr.mira.desai@isha.dev',          name: 'Dr. Mira Desai',      spec: 'Gynecologist',       dept: 'Gynecology',       exp: 6,  fee: 750,  rating: 4.3, qualification: 'MD (Obstetrics & Gynecology)' },
  ],
  'hosp-welcare': [
    { email: 'dr.nisha.shah@welcare.dev',       name: 'Dr. Nisha Shah',      spec: 'Psychiatrist',       dept: 'Psychiatry',       exp: 12, fee: 1000, rating: 4.6, qualification: 'MD (Psychiatry)' },
    { email: 'dr.sameer.khan@welcare.dev',      name: 'Dr. Sameer Khan',     spec: 'Dermatologist',      dept: 'Dermatology',      exp: 5,  fee: 500,  rating: 4.1, qualification: 'MD (Dermatology, Venereology)' },
    { email: 'dr.deepak.rao@welcare.dev',       name: 'Dr. Deepak Rao',      spec: 'Orthopedic Surgeon', dept: 'Orthopedics',      exp: 8,  fee: 750,  rating: 4.3, qualification: 'MS (Orthopedics)' },
  ],
  'hosp-bankers': [
    { email: 'dr.dilip.banker@bankers.dev',     name: 'Dr. Dilip Banker',    spec: 'Cardiologist',       dept: 'Cardiology',       exp: 28, fee: 2000, rating: 4.9, qualification: 'MD, DM (Cardiology), FACC', bio: 'Founder & Chairman. Pioneer in interventional cardiology in Vadodara.' },
    { email: 'dr.kavya.banker@bankers.dev',     name: 'Dr. Kavya Banker',    spec: 'Cardiac Surgeon',    dept: 'Cardiac Surgery',  exp: 14, fee: 2500, rating: 4.7, qualification: 'MS, MCh (Cardiac Surgery)' },
    { email: 'dr.nirav.mehta@bankers.dev',      name: 'Dr. Nirav Mehta',     spec: 'Vascular Surgeon',   dept: 'Vascular Surgery', exp: 12, fee: 1800, rating: 4.5, qualification: 'MS, MCh (Vascular Surgery)' },
  ],
  'hosp-srinath': [
    { email: 'dr.srinath.patel@srinath.dev',    name: 'Dr. Srinath Patel',   spec: 'Gastroenterologist', dept: 'Gastroenterology', exp: 18, fee: 1000, rating: 4.6, qualification: 'MD, DM (Gastroenterology)' },
    { email: 'dr.jayesh.shah@srinath.dev',      name: 'Dr. Jayesh Shah',     spec: 'Laparoscopic Surgeon', dept: 'Laparoscopic Surgery', exp: 14, fee: 1200, rating: 4.5, qualification: 'MS (General Surgery), Fellowship MIS' },
    { email: 'dr.rupa.trivedi@srinath.dev',     name: 'Dr. Rupa Trivedi',    spec: 'General Physician',  dept: 'General Medicine', exp: 8,  fee: 500,  rating: 4.2, qualification: 'MD (General Medicine)' },
  ],
  'hosp-spinetics': [
    { email: 'dr.gaurav.agrawal@spinetics.dev', name: 'Dr. Gaurav Agrawal',  spec: 'Spine Surgeon',      dept: 'Spine Surgery',    exp: 16, fee: 1800, rating: 4.7, qualification: 'MS (Ortho), MCh (Spine Surgery)' },
    { email: 'dr.alok.tiwari@spinetics.dev',    name: 'Dr. Alok Tiwari',     spec: 'Neurosurgeon',       dept: 'Neurosurgery',     exp: 14, fee: 2000, rating: 4.6, qualification: 'MCh (Neurosurgery)' },
    { email: 'dr.shreya.patel@spinetics.dev',   name: 'Dr. Shreya Patel',    spec: 'Orthopedic Surgeon', dept: 'Orthopedics',      exp: 10, fee: 1000, rating: 4.4, qualification: 'MS (Orthopedics)' },
  ],
  'hosp-spectrum': [
    { email: 'dr.ashish.gupta@spectrum.dev',    name: 'Dr. Ashish Gupta',    spec: 'Cardiologist',       dept: 'Cardiology',       exp: 13, fee: 1200, rating: 4.5, qualification: 'MD, DM (Cardiology)' },
    { email: 'dr.sunita.rao@spectrum.dev',      name: 'Dr. Sunita Rao',      spec: 'Gynecologist',       dept: 'Gynecology',       exp: 10, fee: 800,  rating: 4.3, qualification: 'MD, MS (Obstetrics & Gynecology)' },
    { email: 'dr.rohit.kumar@spectrum.dev',     name: 'Dr. Rohit Kumar',     spec: 'Urologist',          dept: 'Urology',          exp: 8,  fee: 1100, rating: 4.3, qualification: 'MS, MCh (Urology)' },
  ],
  'hosp-spandan': [
    { email: 'dr.kartik.shah@spandan.dev',      name: 'Dr. Kartik Shah',     spec: 'Cardiologist',       dept: 'Cardiology',       exp: 11, fee: 1000, rating: 4.4, qualification: 'MD, DM (Cardiology)' },
    { email: 'dr.mamta.pandya@spandan.dev',     name: 'Dr. Mamta Pandya',    spec: 'ENT Specialist',     dept: 'ENT',              exp: 8,  fee: 600,  rating: 4.2, qualification: 'MS (ENT)' },
    { email: 'dr.jatin.patel@spandan.dev',      name: 'Dr. Jatin Patel',     spec: 'Dermatologist',      dept: 'Dermatology',      exp: 6,  fee: 500,  rating: 4.2, qualification: 'MD (Dermatology)' },
  ],
  'hosp-utsav': [
    { email: 'dr.anita.shah@utsav.dev',         name: 'Dr. Anita Shah',      spec: 'Gynecologist',       dept: 'Gynecology',       exp: 15, fee: 900,  rating: 4.6, qualification: 'MD, MS (Obstetrics & Gynecology)' },
    { email: 'dr.prakash.mehta@utsav.dev',      name: 'Dr. Prakash Mehta',   spec: 'Pediatrician',       dept: 'Pediatrics',       exp: 10, fee: 700,  rating: 4.4, qualification: 'MD (Pediatrics)' },
    { email: 'dr.jayantibhai.patel@utsav.dev',  name: 'Dr. Jayantibhai Patel', spec: 'Fertility Specialist', dept: 'Fertility', exp: 12, fee: 1500, rating: 4.5, qualification: 'MD, DGO, Fellowship IVF' },
  ],
  'hosp-krishna': [
    { email: 'dr.sunil.kulkarni@krishna.dev',   name: 'Dr. Sunil Kulkarni',  spec: 'Joint Replacement Surgeon', dept: 'Joint Replacement', exp: 20, fee: 1500, rating: 4.6, qualification: 'MS (Ortho), Fellowship Joint Replacement' },
    { email: 'dr.nisha.dave@krishna.dev',       name: 'Dr. Nisha Dave',      spec: 'Spine Surgeon',      dept: 'Spine Surgery',    exp: 14, fee: 1600, rating: 4.5, qualification: 'MS (Ortho), MCh (Spine)' },
    { email: 'dr.vinay.bhatt@krishna.dev',      name: 'Dr. Vinay Bhatt',     spec: 'General Physician',  dept: 'General Medicine', exp: 8,  fee: 500,  rating: 4.2, qualification: 'MD (General Medicine)' },
  ],
  'hosp-care': [
    { email: 'dr.rakesh.vora@care.dev',         name: 'Dr. Rakesh Vora',     spec: 'Cardiologist',       dept: 'Cardiology',       exp: 18, fee: 1500, rating: 4.6, qualification: 'MD, DM (Cardiology)' },
    { email: 'dr.shilpa.desai@care.dev',        name: 'Dr. Shilpa Desai',    spec: 'Neurologist',        dept: 'Neurology',        exp: 12, fee: 1200, rating: 4.4, qualification: 'MD, DM (Neurology)' },
    { email: 'dr.pravin.patel@care.dev',        name: 'Dr. Pravin Patel',    spec: 'Orthopedic Surgeon', dept: 'Orthopedics',      exp: 10, fee: 900,  rating: 4.3, qualification: 'MS (Orthopedics)' },
  ],
  'hosp-medanta': [
    { email: 'dr.naresh.trehan.v@medanta.dev',  name: 'Dr. Naresh Patel',    spec: 'Cardiologist',       dept: 'Cardiology',       exp: 22, fee: 2000, rating: 4.8, qualification: 'MD, DM (Cardiology), FACC' },
    { email: 'dr.arti.gupta@medanta.dev',       name: 'Dr. Arti Gupta',      spec: 'Oncologist',         dept: 'Oncology',         exp: 16, fee: 2000, rating: 4.6, qualification: 'MD, DM (Medical Oncology)' },
    { email: 'dr.rajiv.kumar@medanta.dev',      name: 'Dr. Rajiv Kumar',      spec: 'Gastroenterologist', dept: 'Gastroenterology', exp: 14, fee: 1600, rating: 4.5, qualification: 'MD, DM (Gastroenterology)' },
  ],
  'hosp-parul': [
    { email: 'dr.kamlesh.patel@parul.dev',      name: 'Dr. Kamlesh Patel',   spec: 'General Surgeon',    dept: 'Surgery',          exp: 18, fee: 600,  rating: 4.3, qualification: 'MS (General Surgery)' },
    { email: 'dr.priti.shah@parul.dev',         name: 'Dr. Priti Shah',      spec: 'Gynecologist',       dept: 'Gynecology',       exp: 14, fee: 500,  rating: 4.3, qualification: 'MD, MS (Obstetrics & Gynecology)' },
    { email: 'dr.tarun.misra@parul.dev',        name: 'Dr. Tarun Misra',     spec: 'Ophthalmologist',    dept: 'Ophthalmology',    exp: 10, fee: 450,  rating: 4.2, qualification: 'MS (Ophthalmology)' },
    { email: 'dr.rina.sharma@parul.dev',        name: 'Dr. Rina Sharma',     spec: 'ENT Specialist',     dept: 'ENT',              exp: 8,  fee: 500,  rating: 4.1, qualification: 'MS (ENT)' },
  ],
  'hosp-dhiraj': [
    { email: 'dr.brijesh.patel@dhiraj.dev',     name: 'Dr. Brijesh Patel',   spec: 'General Physician',  dept: 'General Medicine', exp: 16, fee: 400,  rating: 4.2, qualification: 'MD (General Medicine)' },
    { email: 'dr.rekha.chauhan@dhiraj.dev',     name: 'Dr. Rekha Chauhan',   spec: 'Gynecologist',       dept: 'Gynecology',       exp: 13, fee: 450,  rating: 4.3, qualification: 'MD, MS (Obstetrics & Gynecology)' },
    { email: 'dr.manoj.trivedi@dhiraj.dev',     name: 'Dr. Manoj Trivedi',   spec: 'Cardiologist',       dept: 'Cardiology',       exp: 11, fee: 900,  rating: 4.3, qualification: 'MD, DM (Cardiology)' },
  ],
  // Remaining hospitals — curated demo rosters (T3), specialty matched to hospital departments
  'hosp-gujarat-kidney': [
    { email: 'dr.dinesh.patel@gkf.dev',         name: 'Dr. Dinesh Patel',    spec: 'Nephrologist',       dept: 'Nephrology',       exp: 22, fee: 1500, rating: 4.7, qualification: 'MD, DM (Nephrology)' },
    { email: 'dr.sonal.mehta@gkf.dev',          name: 'Dr. Sonal Mehta',     spec: 'Urologist',          dept: 'Urology',          exp: 14, fee: 1300, rating: 4.5, qualification: 'MS, MCh (Urology)' },
  ],
  'hosp-prakash': [
    { email: 'dr.sunil.patel@prakash.dev',       name: 'Dr. Sunil Patel',     spec: 'General Physician',  dept: 'General Medicine', exp: 10, fee: 400,  rating: 4.1, qualification: 'MD (General Medicine)' },
    { email: 'dr.ritu.joshi@prakash.dev',        name: 'Dr. Ritu Joshi',      spec: 'Pediatrician',       dept: 'Pediatrics',       exp: 8,  fee: 500,  rating: 4.2, qualification: 'MD (Pediatrics)' },
  ],
  'hosp-new-life': [
    { email: 'dr.jyoti.sharma@newlife.dev',      name: 'Dr. Jyoti Sharma',    spec: 'Gynecologist',       dept: 'Gynecology',       exp: 16, fee: 900,  rating: 4.5, qualification: 'MD, MS (Obstetrics & Gynecology)' },
    { email: 'dr.arun.patel@newlife.dev',        name: 'Dr. Arun Patel',      spec: 'Neonatologist',      dept: 'Neonatology',      exp: 12, fee: 800,  rating: 4.4, qualification: 'MD (Pediatrics), DM (Neonatology)' },
  ],
  'hosp-mahavir': [
    { email: 'dr.kiran.patel@mahavir.dev',       name: 'Dr. Kiran Patel',     spec: 'General Surgeon',    dept: 'Surgery',          exp: 12, fee: 600,  rating: 4.1, qualification: 'MS (General Surgery)' },
    { email: 'dr.pooja.jain@mahavir.dev',        name: 'Dr. Pooja Jain',      spec: 'General Physician',  dept: 'General Medicine', exp: 8,  fee: 400,  rating: 4.1, qualification: 'MD (General Medicine)' },
  ],
  'hosp-deep': [
    { email: 'dr.deepak.patel@deep.dev',         name: 'Dr. Deepak Patel',    spec: 'Cardiologist',       dept: 'Cardiology',       exp: 15, fee: 1100, rating: 4.4, qualification: 'MD, DM (Cardiology)' },
    { email: 'dr.hema.shah@deep.dev',            name: 'Dr. Hema Shah',       spec: 'Gynecologist',       dept: 'Gynecology',       exp: 11, fee: 800,  rating: 4.3, qualification: 'MD, MS (Obstetrics & Gynecology)' },
  ],
  'hosp-parijat': [
    { email: 'dr.vasumati.desai@parijat.dev',    name: 'Dr. Vasumati Desai',  spec: 'Gynecologist',       dept: 'Gynecology',       exp: 18, fee: 1000, rating: 4.5, qualification: 'MD, MS (Obstetrics & Gynecology)' },
    { email: 'dr.ankur.patel@parijat.dev',       name: 'Dr. Ankur Patel',     spec: 'Laparoscopic Surgeon', dept: 'Laparoscopic Surgery', exp: 10, fee: 1100, rating: 4.3, qualification: 'MS (General Surgery), Fellowship MIS' },
  ],
  'hosp-sai-hospital': [
    { email: 'dr.nilesh.patel@sai.dev',          name: 'Dr. Nilesh Patel',    spec: 'General Physician',  dept: 'General Medicine', exp: 12, fee: 400,  rating: 4.2, qualification: 'MD (General Medicine)' },
    { email: 'dr.rupali.shah@sai.dev',           name: 'Dr. Rupali Shah',     spec: 'Pediatrician',       dept: 'Pediatrics',       exp: 9,  fee: 500,  rating: 4.2, qualification: 'MD (Pediatrics)' },
  ],
  'hosp-vishwas': [
    { email: 'dr.umesh.patel@vishwas.dev',       name: 'Dr. Umesh Patel',     spec: 'General Physician',  dept: 'General Medicine', exp: 11, fee: 400,  rating: 4.1, qualification: 'MD (General Medicine)' },
    { email: 'dr.seema.trivedi@vishwas.dev',     name: 'Dr. Seema Trivedi',   spec: 'Gynecologist',       dept: 'Gynecology',       exp: 9,  fee: 700,  rating: 4.2, qualification: 'MD (Obstetrics & Gynecology)' },
  ],
  'hosp-anand-hospital': [
    { email: 'dr.anand.patel@anand.dev',         name: 'Dr. Anand Patel',     spec: 'General Physician',  dept: 'General Medicine', exp: 13, fee: 400,  rating: 4.1, qualification: 'MD (General Medicine)' },
    { email: 'dr.shanta.vyas@anand.dev',         name: 'Dr. Shanta Vyas',     spec: 'Orthopedic Surgeon', dept: 'Orthopedics',      exp: 10, fee: 700,  rating: 4.2, qualification: 'MS (Orthopedics)' },
  ],
  'hosp-parshwanath': [
    { email: 'dr.jigar.patel@parshwanath.dev',   name: 'Dr. Jigar Patel',     spec: 'General Physician',  dept: 'General Medicine', exp: 10, fee: 400,  rating: 4.1, qualification: 'MD (General Medicine)' },
    { email: 'dr.meena.parikh@parshwanath.dev',  name: 'Dr. Meena Parikh',    spec: 'ENT Specialist',     dept: 'ENT',              exp: 8,  fee: 500,  rating: 4.2, qualification: 'MS (ENT)' },
  ],
  'hosp-navnirman': [
    { email: 'dr.bharat.patel@navnirman.dev',    name: 'Dr. Bharat Patel',    spec: 'General Physician',  dept: 'General Medicine', exp: 8,  fee: 350,  rating: 4.1, qualification: 'MD (General Medicine)' },
    { email: 'dr.hiral.joshi@navnirman.dev',     name: 'Dr. Hiral Joshi',     spec: 'Pediatrician',       dept: 'Pediatrics',       exp: 6,  fee: 450,  rating: 4.1, qualification: 'MD (Pediatrics)' },
  ],
  'hosp-vms': [
    { email: 'dr.hitesh.shah@vms.dev',           name: 'Dr. Hitesh Shah',     spec: 'General Surgeon',    dept: 'Surgery',          exp: 10, fee: 500,  rating: 4.1, qualification: 'MS (General Surgery)' },
    { email: 'dr.sonal.patel@vms.dev',           name: 'Dr. Sonal Patel',     spec: 'General Physician',  dept: 'General Medicine', exp: 7,  fee: 350,  rating: 4.1, qualification: 'MD (General Medicine)' },
  ],
  'hosp-accord': [
    { email: 'dr.nilesh.rao@accord.dev',         name: 'Dr. Nilesh Rao',      spec: 'Neurologist',        dept: 'Neurology',        exp: 15, fee: 1300, rating: 4.5, qualification: 'MD, DM (Neurology)' },
    { email: 'dr.shriram.verma@accord.dev',      name: 'Dr. Shriram Verma',   spec: 'Neurosurgeon',       dept: 'Neurosurgery',     exp: 18, fee: 1800, rating: 4.6, qualification: 'MCh (Neurosurgery)' },
    { email: 'dr.anjali.patel@accord.dev',       name: 'Dr. Anjali Patel',    spec: 'Orthopedic Surgeon', dept: 'Orthopedics',      exp: 10, fee: 900,  rating: 4.3, qualification: 'MS (Orthopedics)' },
  ],
  'hosp-nikhil': [
    { email: 'dr.nikhil.patel@nikhil.dev',       name: 'Dr. Nikhil Patel',    spec: 'Dermatologist',      dept: 'Dermatology',      exp: 14, fee: 700,  rating: 4.4, qualification: 'MD (Dermatology, Venereology & Leprosy)' },
    { email: 'dr.krupa.trivedi@nikhil.dev',      name: 'Dr. Krupa Trivedi',   spec: 'Cosmetologist',      dept: 'Cosmetology',      exp: 8,  fee: 1200, rating: 4.3, qualification: 'MD (Dermatology), Fellowship Aesthetics' },
  ],
  'hosp-sarvottam': [
    { email: 'dr.sarvottam.patel@sarvottam.dev', name: 'Dr. Sarvottam Patel', spec: 'General Physician',  dept: 'General Medicine', exp: 12, fee: 400,  rating: 4.2, qualification: 'MD (General Medicine)' },
    { email: 'dr.latika.modi@sarvottam.dev',     name: 'Dr. Latika Modi',     spec: 'Gynecologist',       dept: 'Gynecology',       exp: 9,  fee: 700,  rating: 4.2, qualification: 'MD (Obstetrics & Gynecology)' },
  ],
  'hosp-shanti': [
    { email: 'dr.shantilal.patel@shanti.dev',    name: 'Dr. Shantilal Patel', spec: 'General Physician',  dept: 'General Medicine', exp: 15, fee: 400,  rating: 4.2, qualification: 'MD (General Medicine)' },
    { email: 'dr.anuradha.trivedi@shanti.dev',   name: 'Dr. Anuradha Trivedi', spec: 'Gynecologist',      dept: 'Gynecology',       exp: 10, fee: 700,  rating: 4.2, qualification: 'MD (Obstetrics & Gynecology)' },
  ],
  'hosp-apex': [
    { email: 'dr.jigar.desai@apex.dev',          name: 'Dr. Jigar Desai',     spec: 'General Surgeon',    dept: 'General Surgery',  exp: 14, fee: 700,  rating: 4.4, qualification: 'MS (General Surgery), FACS' },
    { email: 'dr.jinal.patel@apex.dev',          name: 'Dr. Jinal Patel',     spec: 'Emergency Physician', dept: 'Emergency Medicine', exp: 8, fee: 600, rating: 4.3, qualification: 'MD (Emergency Medicine)' },
    { email: 'dr.kush.trivedi@apex.dev',         name: 'Dr. Kush Trivedi',    spec: 'Orthopedic Surgeon', dept: 'Orthopedics',      exp: 10, fee: 900,  rating: 4.3, qualification: 'MS (Orthopedics)' },
  ],
  'hosp-druta': [
    { email: 'dr.druta.patel@druta.dev',         name: 'Dr. Druta Patel',     spec: 'General Physician',  dept: 'General Medicine', exp: 9,  fee: 350,  rating: 4.1, qualification: 'MD (General Medicine)' },
    { email: 'dr.leena.shah@druta.dev',          name: 'Dr. Leena Shah',      spec: 'Pediatrician',       dept: 'Pediatrics',       exp: 7,  fee: 400,  rating: 4.1, qualification: 'MD (Pediatrics)' },
  ],
  'hosp-matushri': [
    { email: 'dr.matushri.patel@matushri.dev',   name: 'Dr. Matushri Patel',  spec: 'Gynecologist',       dept: 'Gynecology',       exp: 18, fee: 900,  rating: 4.5, qualification: 'MD, MS (Obstetrics & Gynecology)' },
    { email: 'dr.bhavna.joshi@matushri.dev',     name: 'Dr. Bhavna Joshi',    spec: 'Neonatologist',      dept: 'Neonatology',      exp: 11, fee: 800,  rating: 4.4, qualification: 'MD (Pediatrics), DM (Neonatology)' },
  ],
  'hosp-mayur': [
    { email: 'dr.ramanlal.patel@mayur.dev',      name: 'Dr. Ramanlal Patel',  spec: 'General Physician',  dept: 'General Medicine', exp: 20, fee: 350,  rating: 4.1, qualification: 'MD (General Medicine)' },
    { email: 'dr.seema.patel@mayur.dev',         name: 'Dr. Seema Patel',     spec: 'Pediatrician',       dept: 'Pediatrics',       exp: 10, fee: 400,  rating: 4.1, qualification: 'MD (Pediatrics)' },
  ],
  'hosp-mangalam': [
    { email: 'dr.mangalam.patel@mangalam.dev',   name: 'Dr. Mangalam Patel',  spec: 'Gynecologist',       dept: 'Gynecology',       exp: 14, fee: 750,  rating: 4.3, qualification: 'MD (Obstetrics & Gynecology)' },
    { email: 'dr.arvind.shah@mangalam.dev',      name: 'Dr. Arvind Shah',     spec: 'Pediatrician',       dept: 'Pediatrics',       exp: 9,  fee: 500,  rating: 4.2, qualification: 'MD (Pediatrics)' },
  ],
  'hosp-navapur': [
    { email: 'dr.mahesh.patel@navapur.dev',      name: 'Dr. Mahesh Patel',    spec: 'General Physician',  dept: 'General Medicine', exp: 8,  fee: 350,  rating: 4.1, qualification: 'MD (General Medicine)' },
    { email: 'dr.sunita.joshi@navapur.dev',      name: 'Dr. Sunita Joshi',    spec: 'Gynecologist',       dept: 'Gynecology',       exp: 7,  fee: 500,  rating: 4.1, qualification: 'MD (Obstetrics & Gynecology)' },
  ],
  'hosp-indu': [
    { email: 'dr.indu.patel@indu.dev',           name: 'Dr. Indu Patel',      spec: 'General Physician',  dept: 'General Medicine', exp: 10, fee: 350,  rating: 4.1, qualification: 'MD (General Medicine)' },
    { email: 'dr.harsha.trivedi@indu.dev',       name: 'Dr. Harsha Trivedi',  spec: 'Gynecologist',       dept: 'Gynecology',       exp: 8,  fee: 600,  rating: 4.1, qualification: 'MD (Obstetrics & Gynecology)' },
  ],
  'hosp-narmada': [
    { email: 'dr.narayan.patel@narmada.dev',     name: 'Dr. Narayan Patel',   spec: 'Cardiologist',       dept: 'Cardiology',       exp: 14, fee: 1000, rating: 4.3, qualification: 'MD, DM (Cardiology)' },
    { email: 'dr.gita.joshi@narmada.dev',        name: 'Dr. Gita Joshi',      spec: 'Gynecologist',       dept: 'Gynecology',       exp: 10, fee: 700,  rating: 4.2, qualification: 'MD (Obstetrics & Gynecology)' },
    { email: 'dr.kishor.patel@narmada.dev',      name: 'Dr. Kishor Patel',    spec: 'ENT Specialist',     dept: 'ENT',              exp: 8,  fee: 550,  rating: 4.2, qualification: 'MS (ENT)' },
  ],
  'hosp-savita': [
    { email: 'dr.savita.patel@savita.dev',       name: 'Dr. Savita Patel',    spec: 'General Physician',  dept: 'General Medicine', exp: 11, fee: 350,  rating: 4.1, qualification: 'MD (General Medicine)' },
    { email: 'dr.mihir.trivedi@savita.dev',      name: 'Dr. Mihir Trivedi',   spec: 'Pediatrician',       dept: 'Pediatrics',       exp: 8,  fee: 450,  rating: 4.1, qualification: 'MD (Pediatrics)' },
  ],
};
