-- Phase 15: Extend NotificationType enum with new event types
-- Adds 8 new notification types to support the Phase 15 notification retrofit.

ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'APPOINTMENT_CONFIRMED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'APPOINTMENT_CANCELLED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'QUEUE_YOUR_TURN';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'QUEUE_YOUR_TURN_APPROACHING';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CONSULTATION_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT_RESULT';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BILL_GENERATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PASSPORT_ACCESS_CHANGED';
