/**
 * utils/mockData.js — Complete, rich mock datasets for Frontend-Only / Standalone UI Mode.
 * Enables full access and interactive preview of all 8 role dashboards without a backend.
 */

export const MOCK_USERS = {
  PATIENT: {
    id: 'pat_rahul_123',
    fullName: 'Rahul Verma',
    email: 'patient@healthcareplus.dev',
    role: 'PATIENT',
    phone: '+91 98765 43210',
    gender: 'Male',
    age: 32,
    bloodGroup: 'O+',
    address: '123 Park Street, Vadodara, Gujarat',
    emergencyContact: '+91 98765 00000',
    allergies: ['Penicillin', 'Dust Mites'],
    chronicConditions: ['Mild Asthma'],
  },
  DOCTOR: {
    id: 'doc_anil_456',
    fullName: 'Dr. Anil Shah',
    email: 'dr.anil.shah@sterling.dev',
    role: 'DOCTOR',
    doctorId: 'doc_anil_456',
    specialization: 'Cardiology',
    hospitalId: 'hosp_sterling_01',
    hospitalName: 'Sterling Hospital',
    qualification: 'MD, DM (Cardiology)',
    experienceYears: 14,
    consultationFee: 800,
    rating: 4.9,
    roomNo: 'Cardio-302',
  },
  HOSPITAL_ADMIN: {
    id: 'admin_vikram_789',
    fullName: 'Vikramaditya Admin',
    email: 'admin@sterling.dev',
    role: 'HOSPITAL_ADMIN',
    hospitalId: 'hosp_sterling_01',
    hospitalName: 'Sterling Hospital',
    departmentCount: 8,
    staffCount: 142,
  },
  LAB_STAFF: {
    id: 'lab_suresh_101',
    fullName: 'Suresh Kumar',
    email: 'labstaff@sterling.dev',
    role: 'LAB_STAFF',
    hospitalId: 'hosp_sterling_01',
    hospitalName: 'Sterling Hospital',
    labSection: 'Pathology & Hematology',
  },
  PHARMACIST: {
    id: 'pharm_ramesh_102',
    fullName: 'Ramesh Gupta',
    email: 'pharmacist@sterling.dev',
    role: 'PHARMACIST',
    hospitalId: 'hosp_sterling_01',
    hospitalName: 'Sterling Hospital',
    pharmacyCounter: 'Main Block Counter 1',
  },
  AMBULANCE_DRIVER: {
    id: 'driver_mahesh_103',
    fullName: 'Mahesh Driver',
    email: 'driver@sterling.dev',
    role: 'AMBULANCE_DRIVER',
    hospitalId: 'hosp_sterling_01',
    hospitalName: 'Sterling Hospital',
    vehicleNumber: 'GJ-01-AB-1234',
    status: 'AVAILABLE',
  },
  RECEPTIONIST: {
    id: 'recep_anita_104',
    fullName: 'Anita Roy',
    email: 'receptionist@sterling.dev',
    role: 'RECEPTIONIST',
    hospitalId: 'hosp_sterling_01',
    hospitalName: 'Sterling Hospital',
    deskLocation: 'Main Lobby Helpdesk',
  },
  SUPER_ADMIN: {
    id: 'super_admin_001',
    fullName: 'Super Admin',
    email: 'superadmin@healthcareplus.dev',
    role: 'SUPER_ADMIN',
    accessLevel: 'Global System Root',
  },
};

export const MOCK_HOSPITALS = [
  {
    id: 'hosp_sterling_01',
    name: 'Sterling Hospital',
    type: 'Multi-Specialty',
    address: 'Race Course Road, Vadodara, Gujarat',
    city: 'Vadodara',
    contactPhone: '+91 265 233 4455',
    contactEmail: 'info@sterling.dev',
    rating: 4.8,
    status: 'ACTIVE',
    latitude: 22.3072,
    longitude: 73.1812,
    totalBeds: 250,
    availableBeds: 42,
    crowdLevel: 'MODERATE',
    activeDoctors: 34,
    emergencyAvailable: true,
  },
  {
    id: 'hosp_sunshine_02',
    name: 'Sunshine Global Hospital',
    type: 'Super-Specialty',
    address: 'Near Manisha Crossing, Old Padra Rd, Vadodara',
    city: 'Vadodara',
    contactPhone: '+91 265 222 1100',
    contactEmail: 'contact@sunshine.dev',
    rating: 4.6,
    status: 'ACTIVE',
    latitude: 22.2950,
    longitude: 73.1670,
    totalBeds: 180,
    availableBeds: 19,
    crowdLevel: 'HIGH',
    activeDoctors: 28,
    emergencyAvailable: true,
  },
  {
    id: 'hosp_bhailal_03',
    name: 'Bhailal Amin General Hospital',
    type: 'General Hospital',
    address: 'Alembic Road, Gorwa, Vadodara',
    city: 'Vadodara',
    contactPhone: '+91 265 228 0707',
    contactEmail: 'help@bhailal.dev',
    rating: 4.7,
    status: 'ACTIVE',
    latitude: 22.3310,
    longitude: 73.1550,
    totalBeds: 300,
    availableBeds: 85,
    crowdLevel: 'LOW',
    activeDoctors: 45,
    emergencyAvailable: true,
  },
];

export const MOCK_DOCTORS = [
  {
    id: 'doc_anil_456',
    fullName: 'Dr. Anil Shah',
    email: 'dr.anil.shah@sterling.dev',
    specialization: 'Cardiology',
    hospitalId: 'hosp_sterling_01',
    hospitalName: 'Sterling Hospital',
    qualification: 'MD, DM (Cardiology)',
    experienceYears: 14,
    consultationFee: 800,
    rating: 4.9,
    roomNo: 'Cardio-302',
    isAvailable: true,
    isEmergencyAvailable: true,
  },
  {
    id: 'doc_meena_457',
    fullName: 'Dr. Meena Patel',
    email: 'dr.meena.patel@sterling.dev',
    specialization: 'Neurology',
    hospitalId: 'hosp_sterling_01',
    hospitalName: 'Sterling Hospital',
    qualification: 'MD, DM (Neurology)',
    experienceYears: 11,
    consultationFee: 900,
    rating: 4.8,
    roomNo: 'Neuro-104',
    isAvailable: true,
    isEmergencyAvailable: false,
  },
  {
    id: 'doc_karan_458',
    fullName: 'Dr. Karan Desai',
    email: 'dr.karan.desai@sterling.dev',
    specialization: 'Orthopedics',
    hospitalId: 'hosp_sterling_01',
    hospitalName: 'Sterling Hospital',
    qualification: 'MS (Orthopedics)',
    experienceYears: 9,
    consultationFee: 700,
    rating: 4.7,
    roomNo: 'Ortho-201',
    isAvailable: true,
    isEmergencyAvailable: true,
  },
  {
    id: 'doc_neha_459',
    fullName: 'Dr. Neha Joshi',
    email: 'dr.neha.joshi@sunshine.dev',
    specialization: 'Pediatrics',
    hospitalId: 'hosp_sunshine_02',
    hospitalName: 'Sunshine Global Hospital',
    qualification: 'MD (Pediatrics)',
    experienceYears: 8,
    consultationFee: 650,
    rating: 4.9,
    roomNo: 'Pedia-102',
    isAvailable: true,
    isEmergencyAvailable: false,
  },
];

export const MOCK_APPOINTMENTS = [
  {
    id: 'apt_1001',
    tokenNo: 1,
    patientId: 'pat_rahul_123',
    patientName: 'Rahul Verma',
    patientEmail: 'patient@healthcareplus.dev',
    patientPhone: '+91 98765 43210',
    doctorId: 'doc_anil_456',
    doctorName: 'Dr. Anil Shah',
    specialization: 'Cardiology',
    hospitalId: 'hosp_sterling_01',
    hospitalName: 'Sterling Hospital',
    appointmentDate: new Date().toISOString().split('T')[0],
    slotTime: '10:30 AM',
    status: 'IN_CONSULTATION',
    consultationType: 'IN_PERSON',
    fee: 800,
    symptoms: 'Chest tightness, mild dizziness after workout',
    paymentStatus: 'PAID',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'apt_1002',
    tokenNo: 2,
    patientId: 'pat_priya_124',
    patientName: 'Priya Sharma',
    patientEmail: 'dummy1@healthcareplus.dev',
    patientPhone: '+91 98765 11111',
    doctorId: 'doc_anil_456',
    doctorName: 'Dr. Anil Shah',
    specialization: 'Cardiology',
    hospitalId: 'hosp_sterling_01',
    hospitalName: 'Sterling Hospital',
    appointmentDate: new Date().toISOString().split('T')[0],
    slotTime: '11:00 AM',
    status: 'CONFIRMED',
    consultationType: 'IN_PERSON',
    fee: 800,
    symptoms: 'Routine BP follow up',
    paymentStatus: 'PAID',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'apt_1003',
    tokenNo: 3,
    patientId: 'pat_arjun_125',
    patientName: 'Arjun Mehta',
    patientEmail: 'dummy2@healthcareplus.dev',
    patientPhone: '+91 98765 22222',
    doctorId: 'doc_anil_456',
    doctorName: 'Dr. Anil Shah',
    specialization: 'Cardiology',
    hospitalId: 'hosp_sterling_01',
    hospitalName: 'Sterling Hospital',
    appointmentDate: new Date().toISOString().split('T')[0],
    slotTime: '11:30 AM',
    status: 'CONFIRMED',
    consultationType: 'ONLINE',
    fee: 800,
    symptoms: 'ECG report review',
    paymentStatus: 'PAID',
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_PRESCRIPTIONS = [
  {
    id: 'rx_5001',
    appointmentId: 'apt_1001',
    patientId: 'pat_rahul_123',
    patientName: 'Rahul Verma',
    doctorId: 'doc_anil_456',
    doctorName: 'Dr. Anil Shah',
    hospitalName: 'Sterling Hospital',
    date: new Date().toISOString().split('T')[0],
    diagnosis: 'Mild Hypertension & Stress-induced Tachycardia',
    instructions: 'Take medicines after meals with warm water. Reduce sodium intake.',
    status: 'ACTIVE',
    medicines: [
      { name: 'Telmisartan 40mg', dosage: '1 tablet', frequency: 'Once daily (Morning)', duration: '30 days', price: 120 },
      { name: 'Atorvastatin 10mg', dosage: '1 tablet', frequency: 'Once daily (Night)', duration: '30 days', price: 180 },
      { name: 'Multivitamin Complex', dosage: '1 capsule', frequency: 'Once daily (Afternoon)', duration: '15 days', price: 90 },
    ],
  },
];

export const MOCK_LAB_REQUESTS = [
  {
    id: 'lab_req_7001',
    appointmentId: 'apt_1001',
    patientId: 'pat_rahul_123',
    patientName: 'Rahul Verma',
    patientEmail: 'patient@healthcareplus.dev',
    doctorId: 'doc_anil_456',
    doctorName: 'Dr. Anil Shah',
    hospitalId: 'hosp_sterling_01',
    hospitalName: 'Sterling Hospital',
    status: 'PENDING',
    createdAt: new Date().toISOString(),
    items: [
      { testName: 'Lipid Profile Screen', category: 'Biochemistry', estimatedPrice: 650 },
      { testName: 'Complete Blood Count (CBC)', category: 'Hematology', estimatedPrice: 350 },
      { testName: 'HbA1c Glycated Hemoglobin', category: 'Endocrinology', estimatedPrice: 500 },
    ],
  },
  {
    id: 'lab_req_7002',
    appointmentId: 'apt_1002',
    patientId: 'pat_priya_124',
    patientName: 'Priya Sharma',
    patientEmail: 'dummy1@healthcareplus.dev',
    doctorId: 'doc_meena_457',
    doctorName: 'Dr. Meena Patel',
    hospitalId: 'hosp_sterling_01',
    hospitalName: 'Sterling Hospital',
    status: 'PROCESSING',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    items: [
      { testName: 'Serum Electrolytes', category: 'Biochemistry', estimatedPrice: 400 },
      { testName: 'Thyroid Profile (T3, T4, TSH)', category: 'Endocrinology', estimatedPrice: 750 },
    ],
  },
  {
    id: 'lab_req_7003',
    appointmentId: 'apt_1003',
    patientId: 'pat_arjun_125',
    patientName: 'Arjun Mehta',
    patientEmail: 'dummy2@healthcareplus.dev',
    doctorId: 'doc_karan_458',
    doctorName: 'Dr. Karan Desai',
    hospitalId: 'hosp_sterling_01',
    hospitalName: 'Sterling Hospital',
    status: 'COMPLETED',
    reportUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    items: [
      { testName: 'X-Ray Right Knee Joint', category: 'Radiology', estimatedPrice: 500 },
    ],
  },
];

export const MOCK_PHARMACY_ORDERS = [
  {
    id: 'ph_ord_9001',
    prescriptionId: 'rx_5001',
    patientId: 'pat_rahul_123',
    patientName: 'Rahul Verma',
    hospitalId: 'hosp_sterling_01',
    hospitalName: 'Sterling Hospital',
    status: 'PENDING',
    totalAmount: 390,
    createdAt: new Date().toISOString(),
    items: [
      { medicineName: 'Telmisartan 40mg', quantity: 30, unitPrice: 4, totalPrice: 120 },
      { medicineName: 'Atorvastatin 10mg', quantity: 30, unitPrice: 6, totalPrice: 180 },
      { medicineName: 'Multivitamin Complex', quantity: 15, unitPrice: 6, totalPrice: 90 },
    ],
  },
  {
    id: 'ph_ord_9002',
    prescriptionId: 'rx_5002',
    patientId: 'pat_priya_124',
    patientName: 'Priya Sharma',
    hospitalId: 'hosp_sterling_01',
    hospitalName: 'Sterling Hospital',
    status: 'PREPARING',
    totalAmount: 520,
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    items: [
      { medicineName: 'Amoxicillin 500mg', quantity: 20, unitPrice: 15, totalPrice: 300 },
      { medicineName: 'Paracetamol 650mg', quantity: 20, unitPrice: 11, totalPrice: 220 },
    ],
  },
];

export const MOCK_EMERGENCY_REQUESTS = [
  {
    id: 'sos_8001',
    patientId: 'pat_rahul_123',
    patientName: 'Rahul Verma',
    patientPhone: '+91 98765 43210',
    pickupAddress: 'RC Dutt Road, Alkapuri, Vadodara',
    latitude: 22.3100,
    longitude: 73.1800,
    destHospitalId: 'hosp_sterling_01',
    destHospitalName: 'Sterling Hospital',
    status: 'DRIVER_ASSIGNED',
    driverId: 'driver_mahesh_103',
    driverName: 'Mahesh Driver',
    driverPhone: '+91 98111 22233',
    vehicleNumber: 'GJ-01-AB-1234',
    etaMinutes: 8,
    requestedAt: new Date(Date.now() - 300000).toISOString(),
    ambulance: {
      id: 'amb_01',
      vehicleNumber: 'GJ-01-AB-1234',
      currentLatitude: 22.3150,
      currentLongitude: 73.1850,
      driver: {
        user: { fullName: 'Mahesh Driver' },
        phone: '+91 98111 22233',
      },
    },
  },
];

export const MOCK_STAFF = [
  { id: 'st_1', fullName: 'Dr. Anil Shah', role: 'DOCTOR', email: 'dr.anil.shah@sterling.dev', department: 'Cardiology', status: 'ACTIVE' },
  { id: 'st_2', fullName: 'Suresh Kumar', role: 'LAB_STAFF', email: 'labstaff@sterling.dev', department: 'Pathology', status: 'ACTIVE' },
  { id: 'st_3', fullName: 'Ramesh Gupta', role: 'PHARMACIST', email: 'pharmacist@sterling.dev', department: 'Pharmacy', status: 'ACTIVE' },
  { id: 'st_4', fullName: 'Mahesh Driver', role: 'AMBULANCE_DRIVER', email: 'driver@sterling.dev', vehicleNumber: 'GJ-01-AB-1234', status: 'ACTIVE' },
  { id: 'st_5', fullName: 'Anita Roy', role: 'RECEPTIONIST', email: 'receptionist@sterling.dev', department: 'Front Desk', status: 'ACTIVE' },
];

export const MOCK_DEPARTMENTS = [
  { id: 'dep_1', name: 'Cardiology', headName: 'Dr. Anil Shah', doctorCount: 6, bedCount: 40 },
  { id: 'dep_2', name: 'Neurology', headName: 'Dr. Meena Patel', doctorCount: 4, bedCount: 30 },
  { id: 'dep_3', name: 'Orthopedics', headName: 'Dr. Karan Desai', doctorCount: 5, bedCount: 35 },
  { id: 'dep_4', name: 'Pediatrics', headName: 'Dr. Neha Joshi', doctorCount: 4, bedCount: 25 },
];

export const MOCK_MEDICINES = [
  { id: 'med_1', name: 'Telmisartan 40mg', category: 'Cardiovascular', stock: 450, price: 4.0 },
  { id: 'med_2', name: 'Atorvastatin 10mg', category: 'Lipid Lowering', stock: 320, price: 6.0 },
  { id: 'med_3', name: 'Amoxicillin 500mg', category: 'Antibiotics', stock: 200, price: 15.0 },
  { id: 'med_4', name: 'Paracetamol 650mg', category: 'Analgesics', stock: 1200, price: 2.5 },
  { id: 'med_5', name: 'Metformin 500mg', category: 'Antidiabetic', stock: 600, price: 3.5 },
];

export const MOCK_LAB_TESTS = [
  { id: 'test_1', name: 'Complete Blood Count (CBC)', category: 'Hematology', price: 350, turnaroundHours: 4, masterTest: { category: { name: 'Hematology' } } },
  { id: 'test_2', name: 'Lipid Profile Screen', category: 'Biochemistry', price: 650, turnaroundHours: 6, masterTest: { category: { name: 'Biochemistry' } } },
  { id: 'test_3', name: 'HbA1c Glycated Hemoglobin', category: 'Endocrinology', price: 500, turnaroundHours: 5, masterTest: { category: { name: 'Endocrinology' } } },
  { id: 'test_4', name: 'Thyroid Profile (T3, T4, TSH)', category: 'Endocrinology', price: 750, turnaroundHours: 8, masterTest: { category: { name: 'Endocrinology' } } },
  { id: 'test_5', name: 'X-Ray Chest PA View', category: 'Radiology', price: 450, turnaroundHours: 1, masterTest: { category: { name: 'Radiology' } } },
];

export const MOCK_BILLS = [
  {
    id: 'bill_01',
    billNumber: 'INV-2026-0089',
    hospitalId: 'hosp_sterling_01',
    hospitalName: 'Sterling Hospital',
    patientName: 'Rahul Verma',
    totalAmount: 1250,
    paidAmount: 1250,
    status: 'PAID',
    paymentMethod: 'UPI / Razorpay',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    payments: [
      { id: 'pay_01', razorpayOrderId: 'order_mock_01', status: 'COMPLETED', amount: 1250 }
    ],
    items: [
      { description: 'OPD Consultation Fee - Dr. Anil Shah', amount: 800 },
      { description: 'Complete Blood Count (CBC) Lab Test', amount: 450 },
    ],
  },
  {
    id: 'bill_02',
    billNumber: 'INV-2026-0090',
    hospitalId: 'hosp_sterling_01',
    hospitalName: 'Sterling Hospital',
    patientName: 'Rahul Verma',
    totalAmount: 620,
    paidAmount: 0,
    status: 'PENDING',
    paymentMethod: 'PENDING',
    createdAt: new Date().toISOString(),
    payments: [
      { id: 'pay_02', razorpayOrderId: 'order_mock_02', status: 'CREATED', amount: 620 }
    ],
    items: [
      { description: 'Prescription Pharmacy Order (Amoxicillin, Paracetamol)', amount: 620 },
    ],
  },
];

export const MOCK_ANALYTICS = {
  totalPatients: 1420,
  activeAppointments: 18,
  todayRevenue: 42800,
  completedConsultations: 34,
  labTestsPending: 6,
  pharmacyOrdersPending: 4,
  ambulanceDispatchesToday: 3,
  systemHealth: '100% Operational',
};
